### ISSUE TITLE
Archlinux compile error

### ISSUE THREAD

**Issue by HenrySteinmetz** [JakeStanger/ironbar#107]
**Describe the bug**
> Compile errors during installation

**To Reproduce**
1.  try to install with aur or cargo or try to compile from source

**Expected behavior**
> A normal install

**System information:**
 - Distro: Arch Linux
- Compositor: Hyprland
 - Ironbar version: 0.11

**Additional context**
> I already checked if had al the build dependencys and even checked the rust errors and found out that one is related to an import problem and the other is trying to use a private function out of scope

**Screenshot**
![error](https://user-images.githubusercontent.com/121169024/232223678-4fa2f72b-b8b3-45da-b005-30c3bc0abaf0.png)

**Comment by JakeStanger** [comment]
This looks like it's caused by an old version of the rust toolchain. Can you try updating that (`rustup update`if you installed via rustup) and see if that resolves it?

**Comment by HenrySteinmetz** [comment]
yeah thanks that solved it I'm closing the issue
