### ISSUE TITLE
Does not work with `swaybar_command`

### ISSUE THREAD

**Issue by JakeStanger** [JakeStanger/ironbar#11]
The bar does not start when setting in sway config like so:

```
bar {
  swaybar_command ironbar
}
```

Can workaround by executing directly (I think):
```
exec ironbar
```

**Comment by quietvoid** [comment]
It seems that since the addition of IPC control, launching ironbar with `swaybar_command` always fails because of unexpected arguments.

**Comment by JakeStanger** [comment]
Oh darn, I never considered that & haven't touched Sway in a while because it's plagued with issues on Nvidia. I'll re-open this and have a look into it as soon as I can. Thanks for letting me know.

**Comment by quietvoid** [comment]
There's no hurry for me. I can easily work around it with an extra shell script.
