### ISSUE TITLE
Separate slider value from display?

### ISSUE THREAD

**Issue by JustSimplyKyle** [JakeStanger/ironbar#115]
**Is your feature request related to a problem? Please describe.**
I just want a volume bar, but I don't want it to have numbers floating on top?

**Describe the solution you'd like**
The non-breaking solution would be to let value accept floating point *AND* empty strings.
Imho, the better solution would be to create a separate field called `display`(or `label`) that accepts a string.
(and optionally gives the value by argument, `$0`) 

**Additional context**
If this doesn't end up being implemented? Please tell me how to style this.
![image](https://user-images.githubusercontent.com/68589851/233788402-04d999dc-a3b9-40f3-a98a-d13f2fa813aa.png)

**Comment by JakeStanger** [comment]
The easier alternative here is just to add a `show_label`  option which you can set to false to hide the label. GTK doesn't really offer much control over the label beyond that.

**Comment by JustSimplyKyle** [comment]
uhh, why exactly is this closed? is the new option just not documented?
Although I did find a workaround. Just remeove it in css!
```css
scale value {
	color: #77a5bf;
	font-size: 0px;
}
```

**Comment by yavko** [comment]
> uhh, why exactly is this closed? is the new option just not documented?

I'm not sure myself, I checked the code and there is no `show_label` option added, all the code in the PR seems to be related to a `step` option.

**Comment by JakeStanger** [comment]
There was a discussion that lead to the linked PR, got them muddled
