### ISSUE TITLE
Message:  range end index 2 out of range for slice of length 1

### ISSUE THREAD

**Issue by JustSimplyKyle** [JakeStanger/ironbar#117]
**Describe the bug**
`label = "{{~/.config/eww/scripts/wifi --ESSID}} "`
Mind the space after the script! And it well crashes.
```bash
2023-04-22T15:03:01.457678Z ERROR ironbar::logging: The application panicked (crashed).
Message:  range end index 2 out of range for slice of length 1
Location: src/dynamic_string.rs:91
```

**To Reproduce**
1. put the label in config
2. run it
3. crash

**Expected behavior**
doesn't crash.

**System information:**
- Ironbar version: 0.11.0(git)
- Compositor: Hyprland
- Distro: Arch linux 6.2.1-273-tkg-bore

**Configuration**
> Share your bar configuration and stylesheet as applicable:

<details><summary>Config</summary>

```
    $internet = {
        type="custom"
        class="internet"
        bar = [
        {
            type = "label"
            label = "{{~/.config/eww/scripts/wifi --ESSID}} "
            on_mouse_enter = "rm /tmp/internet.lock"
            on_mouse_exit = "touch /tmp/internet.lock"
            show_if = "0:~/.config/ironbar/states/internet/state.sh"
        }
        {
        type = "label"
            label = "{{~/.config/eww/scripts/wifi --ICON}}"
            on_click_right = "pavucontrol"
            on_mouse_enter = "rm /tmp/internet.lock"
            on_mouse_exit = "touch /tmp/internet.lock"
        }
        ]
    }

```
</details>

**Additional context**
` label = "{{~/.config/eww/scripts/wifi --ESSID}}  "`
This resolves the issue.

**Comment by JakeStanger** [comment]
Thanks, will have a fix merged in a few mins
