### ISSUE TITLE
Support for normal module types in custom modules.

### ISSUE THREAD

**Issue by JustSimplyKyle** [JakeStanger/ironbar#131]
**Is your feature request related to a problem? Please describe.**
I want to create a custom module that has the module `focused`, because I want to make animations!
And to make those animations, they have to be in the same top-level css class.

**Describe the solution you'd like**
pseudo config:
```corn
$test = {
    type = "custom"
    class = "focus"
    on_mouse_enter = "rm /tmp/window.lock"
    on_mouse_exit = "touch /tmp/window.lock"
    bar = [
        {
            type = "focused"
            show_icon = true
            show_title = true
            icon_size = 24
            icon_theme = "Paper"
        }
        {
            type = "label"
            transition_duration = 400
            label = " Maximize, Close"
            show_if = "0:~/.config/ironbar/states/window/state.sh"
        }
    ]
}
``` 
Another alternative solution would be making it possible to have a "box" to contain normal modules.

Additonal Context:
https://github.com/JakeStanger/ironbar/issues/34
that issue has been resolved, but it turned into supporting script instead

**Comment by JakeStanger** [comment]
This is an eventual goal. What I'd like to do is have every custom widget actually be a standalone module, and then custom is purely composed out of modules. That should hopefully simplify things a bit from both a code and user perspective.

**Comment by yavko** [comment]
It's been 9 months so I just wanna know if this is still planned

**Comment by JakeStanger** [comment]
> It's still going to be a long time before I pick this up though.

, he lied

**Comment by yavko** [comment]
> > It's still going to be a long time before I pick this up though.
> 
> , he lied

yay
