### ISSUE TITLE
Focused and Launcher modules attempt to render unknown image types.

### ISSUE THREAD

**Issue by A-Cloud-Ninja** [JakeStanger/ironbar#146]
**Describe the bug**
Possibly due to flatpak'd versions of Spotify and Discord (and otherwise icon-missing applications), apps that don't properly have an icon do not get verified, and an error is printed.
**To Reproduce**
1. Use launcher or focused with show_icon
2. Have an app that either doesn't have an icon or otherwise isn't in the correct location
3. Launch ironbar, observe errors upon loading icons for the app.

**Expected behavior**
Either a warning and/or discarding or sanitizing of related items

**System information:**
 - Distro: Arch
- Compositor: Hyprland
 - Ironbar version: `Ironbar version 0.12.1` via `ironbar --version` on `aur/ironbar-git`

**Configuration**
https://f.cloudninja.pw/ironbar_config.json

**Screenshot**
![SuccinctIncompetentKoala](https://user-images.githubusercontent.com/5809177/236894723-ab739d9c-fbf1-490e-b0c4-a046ae755309.png)

**Comment by JakeStanger** [comment]
Will improve the error handling around this to try and rule out some of the non-errors, reduce missing images to warnings, and avoid printing the full stack.

**Comment by TheSunCat** [comment]
When focusing an app for which it cannot find an icon (though Anyrun does find the icon), ironbar does indeed just print a warning, however it still renders the icon for the last focused app.

For example, if I move focus from Firefox to Supersonic (AUR package `supersonic-desktop`), ironbar fails to find Supersonic's icon and instead renders Firefox's icon.

**Comment by JakeStanger** [comment]
Thanks for reporting. I've opened an issue to track that and should get it sorted soon.
