### ISSUE TITLE
All nerdfont icons used in ironbar break with new version of nerdfont

### ISSUE THREAD

**Issue by yavko** [JakeStanger/ironbar#152]
**Describe the bug**

Yeah so the nerdfont devs released a new release (0.3.0), and now all the icons don't work (appear as CJK or Arabic) :) https://github.com/ryanoasis/nerd-fonts/issues/365
https://www.nerdfonts.com/releases

**To Reproduce**
1. update nerdfont
2. see

**Expected behavior**

Icons aren't CJK or Arabic

**System information:**
 - Distro: NixOS unstable
- Compositor: Hyprland
 - Ironbar version: master
 
**Screenshots**
![image](https://github.com/JakeStanger/ironbar/assets/15178513/c10961f1-523f-4201-8997-af68c45f9d35)
> play button is fine cuz i overwrote that one with system icon theme

![image](https://github.com/JakeStanger/ironbar/assets/15178513/ca50b302-ef9e-4679-adc6-22d7713318e2)
> song title should be cjk here, but first chars are brokey

**Comment by JakeStanger** [comment]
Correct me if I'm wrong, but I don't think this is in scope of ironbar (outside the docs), since it doesn't handle fonts beyond loading the CSS styles. 

I'll look to see if/how this affects the examples and update those.

**Comment by yavko** [comment]
> Correct me if I'm wrong, but I don't think this is in scope of ironbar (outside the docs), since it doesn't handle fonts beyond loading the CSS styles. 
> 
> I'll look to see if/how this affects the examples and update those.

It is, the Unicode values have changed

**Comment by yavko** [comment]
If you update your fonts you will see this too

**Comment by JakeStanger** [comment]
> It is, the Unicode values have changed

Ah of course, I forgot there are chars coded into the defaults :facepalm: I'm with you now

**Comment by JakeStanger** [comment]
Think that's got 'em. From memory / a quick search I don't think there are any outside of the music module, and nerdfix didn't find anything else. Let me know if you know there's anything I've missed
