### ISSUE TITLE
[Focused] show_icon:false leaves an empty GtkImage to take up space

### ISSUE THREAD

**Issue by A-Cloud-Ninja** [JakeStanger/ironbar#184]
**Describe the bug**
focused modules `show_icon` set to false leaves an empty GtkImage, resulting in awkward spacing.

**To Reproduce**
Basically as above, set `show_icon` to false for a focused module, observe an extra GtkImage (put a border on the widget, or look at the debug inspector)

**Expected behavior**
It can be worked around with 
```css
#bar #center .icon {
    margin-right: -25px;
}
```
or similar, but I think removing the image if that's set would be optimal, as this might not work outside of my usecase.

**System information:**
Arch, ironbar-git just re-built

**Comment by JakeStanger** [comment]
Thanks for logging, but got that covered in #169 already :)
