### ISSUE TITLE
Music popup classes duplicated across certain elements

### ISSUE THREAD

**Issue by A-Cloud-Ninja** [JakeStanger/ironbar#185]
**Describe the bug**

The selector `.popup-music .title .label` targets both the icon and text labels and requires more specific selection when writing CSS.
![Ironbar_Popup_Debug](https://github.com/JakeStanger/ironbar/assets/5809177/1d8af82d-b48e-4f56-9d8a-bc9bef600182)

The docs specifically note `.popup-music .title .label | Track title label inside popup box`

**Comment by JakeStanger** [comment]
Looks like the `.icon` is getting the `.label` class for some reason. Should be an easy fix

**Comment by JakeStanger** [comment]
More to it than I thought, but I've changed some classes around and added some new ones that should resolve this.
