### ISSUE TITLE
Unable to build

### ISSUE THREAD

**Issue by ferrreo** [JakeStanger/ironbar#198]
**Describe the bug**
Currently unable build this using cargo

**To Reproduce**
Clone repo, even at the last release tag
cargo build --release

This is the output:
![image](https://github.com/JakeStanger/ironbar/assets/482133/40a8a726-0dab-4aee-ab93-922123fe7b8b)

**Comment by JakeStanger** [comment]
That's my bad. The Stray PR got merged and I deleted my branch without thinking.

I've just restored it so it should work again now.

**Comment by ferrreo** [comment]
Working now thanks!
