### ISSUE TITLE
Height option for custom modules/widgets

### ISSUE THREAD

**Issue by Preetam-Das** [JakeStanger/ironbar#204]
Currently, adding a custom module increases the bars the total height which is annoying. I use a laptop with a small screen so the slight increase in height matters a lot. I want to add a custom power menu but the height increases when i place a button widget on the bar. Is there a way to avoid that or is there a way I can decrease the button's height so that total height of the bar does not increase??

Great project BTW !! :hugs:

**Comment by JakeStanger** [comment]
Hey, GTK will size a module automatically, and will push it out to ensure its child content fits - you can set a min size, but not a max.

Most likely what's happening is you have some padding/margin on the module, or the font size is too large, and that's pushing the module out.

If you want me to take a look I can - just share your config/style.

**Comment by Preetam-Das** [comment]
Thanks for replying early. Yea padding/margin seemed to be the issue. I added   `* {padding: 0px; margin: 0px}` to my style.css and now the button does not push out the bar's height.

Thanks for helping out, closing the issue now. :smile:

**Comment by azertyfun** [comment]
Just FYI for anyone who stumbles upon this issue, I have narrowed down the CSS a little further:

```css
.container box * {
    min-height: 0;
}
```
