### ISSUE TITLE
[Custom] Image buttons

### ISSUE THREAD

**Issue by Preetam-Das** [JakeStanger/ironbar#207]
Would be cool if we can use image/icons as button labels. 

One alternative can be using `box` and `image` widget and using the `on_left_click` module level option to make an image button, but then we will lose the ability to use `popups` (probably can be achieved by using by scripts/variables but fells hackish).

Instead like the `image` widget the `button` can have `src` and `size` attributes and we can have cool image buttons. :)

**Comment by yavko** [comment]
Also support for popups being opened from IPC isn't supported yet, so this would have to be added lol.

**Comment by JakeStanger** [comment]
Buttons allow a single child element, but that element can be a Box, so my thinking is to add a `widgets` property that works the same way as the box currently and then you can go wild composing whatever you want inside a button.

So something like

```corn
$custom = {
  bar = [
    { 
      type = "button" 
      widgets = [
        { type = "image" src = "..." }
        { type = "label" label = "..." }
      ]
    }
  ]
}
```

**Comment by yavko** [comment]
> Buttons allow a single child element, but that element can be a Box, so my thinking is to add a `widgets` property that works the same way as the box currently and then you can go wild composing whatever you want inside a button.
> 
> So something like
> 
> ```corn
> $custom = {
>   type = "custom"
>   bar = [
>     { 
>       type = "button" 
>       widgets = [
>         { type = "image" src = "..." }
>         { type = "label" label = "..." }
>       ]
>     }
>   ]
> }
> ```
> 

Wouldn't that also require there to be a orientation property

**Comment by JakeStanger** [comment]
That wasn't a complete example above, just the min case. `orientation` is optional, so it'd probs be the same on the button.

**Comment by daktras420** [comment]
sorry for the question i am trying to make sense of this. to use this to make a custom power button that launches for example wlogout and a start button that would use woffi or nwg-draw? 
custom = {
  type = "custom"
  bar = [
    { 
      type = "button" 
      widgets = [
        { type = "image" src = "location of icon png" }
        { type = "label" label = "powerbtn" }
      on_click=: "wlogout"
      ]
    }
  ]
}

**Comment by JakeStanger** [comment]
If I'm understanding correctly you're asking for an example for those scenarios? To be clear this isn't implemented yet, but I think you'd eventually want something like:

```corn
{
	custom = {
		type = "custom"
		bar = [
			{
				type = "button"
				widgets = [ 
					{ type = "image" src = "location of icon png" }
        				{ type = "label" label = "logout" }
				]
				on_click = "wlogout"
			}
			{
				type = "button"
				widgets = [ 
					{ type = "image" src = "location of icon png" }
        				{ type = "label" label = "wofi menu" }
				]
				on_click = "wofi"
			}

		]
	}
}
```
