### ISSUE TITLE
[Clock] Format doesn't respect locale

### ISSUE THREAD

**Issue by donovanglover** [JakeStanger/ironbar#211]
**Describe the bug**
Format doesn't change based on locale. The calendar popup uses the correct locale, however.

**To Reproduce**
```
LANG=ja_JP.UTF-8 ironbar
```

**Expected behavior**
Correct locale should be used

**System information:**
 - Distro: NixOS
- Compositor: Hyprland
 - Ironbar version: https://github.com/JakeStanger/ironbar/commit/7f4a816379cfd991aa8b9fe23f1a6917ccc387fc

**Configuration**

```
{
  "type": "clock",
  "format": "%c"
}
```

**Comment by JakeStanger** [comment]
Thanks for reporting! Once the above is merged, `LC_TIME` and `LOCALE` should be respected, or you can manually set in the config.
