### ISSUE TITLE
[Onboarding] Start ironbar with default config if one doesn't exist

### ISSUE THREAD

**Issue by donovanglover** [JakeStanger/ironbar#219]
**Is your feature request related to a problem? Please describe.**
Currently when a user tries `ironbar` for the first time they're greeted with an error message.

**Describe the solution you'd like**
Ironbar should create a default config if one doesn't exist and start as expected.

**Describe alternatives you've considered**
Alternatively show a more helpful error message to the user, possibly asking them to run a command to copy an example config.

**Comment by JakeStanger** [comment]
The linked PR handles this well enough for now I think - it includes a hard-coded config, so it's not going to get forgotten in any breaking changes etc. It provides a bare minimum (focused + clock) and informs the user it's the default config. Some logging has also been added with a link to the wiki to make this obvious.
