### ISSUE TITLE
[Launcher] Popup still visible when no longer hovering over icon

### ISSUE THREAD

**Issue by donovanglover** [JakeStanger/ironbar#224]
**Describe the bug**
When an application is on the leftmost or rightmost side of the bar with multiple windows, the popup for that application shows indefinitely when leaving the module area.

**To Reproduce**

1. Hover over leftmost/rightmost applications with multiple windows while the bar is centered
2. Observe popup staying until ironbar is clicked or another application icon is hovered

**Expected behavior**
Popup disappears when not hovered over

**System information:**

- Distro: NixOS
- Compositor: Hyprland
- Ironbar version: https://github.com/JakeStanger/ironbar/commit/f8d8c063008340922b20aa665d8f893ab63e82d7

**Configuration**
```json
      "center": [
        {
          "type": "launcher"
        }
      ]
```

**Comment by JakeStanger** [comment]
I'm aware of this one and it's always been a bit of a head scratcher to solve. I'm hoping the upcoming popup changes for the IPC will make fixing this easier, so should have it sorted soon™

**Comment by JakeStanger** [comment]
Not sure what I was on before, was a very easy fix...should have it merged shortly.
