### ISSUE TITLE
[Launcher] Issues with focused state of icons

### ISSUE THREAD

**Issue by donovanglover** [JakeStanger/ironbar#225]
**Describe the bug**
Making one issue to track focus bugs since I encountered a few.

1. Applications with multiple windows open keep their focused state if you close a window that results in an empty workspace while other windows of that application remain.
2. Applications that are listed under `favorites` don't gain their focused state when opened.
3. At least [one](https://search.nixos.org/packages?show=osu-lazer-bin) application remains permanently focused even after restarting ironbar. Application isn't visible with `hyprctl clients`.
4. https://github.com/JakeStanger/ironbar/issues/213 (already reported)

**System information:**

- Distro: NixOS
- Compositor: Hyprland
- Ironbar version: https://github.com/JakeStanger/ironbar/commit/f8d8c063008340922b20aa665d8f893ab63e82d7

**Comment by donovanglover** [comment]
I haven't been able to reproduce 3 again. Not sure what happened but when that issue occurred I could only fix it by restarting Hyprland.

**Comment by JakeStanger** [comment]
Thanks for reporting. The linked PR will resolve issues 1, 2, and 4.

I'm *hoping* that it might also catch 3, although I've never seen that myself. If you do hit 3 again, let me know.

**Comment by donovanglover** [comment]
Looks like https://github.com/JakeStanger/ironbar/pull/238/commits/6f57ad47ac30348c0ae2b7dba35d5ffdbf96f72d didn't fully fix issue 2. The launcher only sets the focus state the first time an application is launched and not subsequent times. Not all programs have this behavior, but thunar and spek do.

**Comment by JakeStanger** [comment]
Darn okay, thanks for testing and letting me know. I'll re-open this and hopefully get it patched in the next few days.

**Comment by JakeStanger** [comment]
@donovanglover I'm struggling to understand/repro the issue you're experiencing. Are you able to send through the steps / some screenshots / a quick screen recording please?

**Comment by donovanglover** [comment]
I might try to fix it myself later. Basically if I open thunar and close it and open it again then it's not focused in ironbar but is in hyprland. Fixed by doing other events like toggling float.
