### ISSUE TITLE
[Launcher] Incorrect icons being used

### ISSUE THREAD

**Issue by donovanglover** [JakeStanger/ironbar#228]
**Describe the bug**
For example, if I add an `a.b.c`  favorite I get a librewolf icon. [Memento](https://ripose-jp.github.io/Memento/) uses an htop icon, which I assume is because the class name is `projects.ripose.`. Any programs that have the class name `.program-wrapped` appear to be broken as well.

**To Reproduce**
1. Open `memento` or use a random string of characters as a favorite

**Expected behavior**
Incorrect icons should never be visible to the user. How about an icon indicating that none was found instead?

**System information:**
 - Distro: NixOS
- Compositor: Hyprland
 - Ironbar version: https://github.com/JakeStanger/ironbar/commit/abf490b04eda87841639c29893dda98408805a3d

**Additional context**
The `memento.desktop` file has an `Icon=memento` field. How feasible is it to use this instead of the app_id?

Would it be better to let users specify their own class name and icon overrides? Should these overrides be mapped to desktop files?

**Comment by JakeStanger** [comment]
>  The memento.desktop file has an Icon=memento field. How feasible is it to use this instead of the app_id?

This *should* be happening if a reasonable match isn't found by filename. I suspect filenames are currently matching a bit too eagerly, and I'll need to tone this down to resolve this.
