### ISSUE TITLE
Regex support in different modules

### ISSUE THREAD

**Issue by yavko** [JakeStanger/ironbar#229]
**Is your feature request related to a problem? Please describe.**

Sometimes you like to write less or just do matching idk

**Describe the solution you'd like**

In module fields that it makes sense in regex matching could be added if detected that it starts in ends in `/` ex `/ironbar is .*/`

**Describe alternatives you've considered**

Maybe a different syntax?

**Additional context**

This comes from #147

**Comment by JakeStanger** [comment]
Which config options do you think would benefit from this? Or are there new options you have in mind that should be added and use this?

**Comment by JakeStanger** [comment]
Going to close this due to lack of detail & too wide a scope. If there is opportunity to add regex somewhere specific, feel free to open an issue around that.
