### ISSUE TITLE
Example CSS misses some elements with default GTK theme 

### ISSUE THREAD

**Issue by JakeStanger** [JakeStanger/ironbar#264]
**Describe the bug**
If you do not set a system GTK theme and run using the example config/style, there are a number of white patches in amongst the black. 

**To Reproduce**
1. Ensure no system GTK theme is set
2. Grab the example `style.css` from the repo
3. Launch Ironbar

**Expected behavior**
The provided CSS should be as consistent as possible across GTK themes, and at the very least work for a default theme.

**Comment by pinkcreeper100** [comment]
is this like what I have above the widgets?
![image](https://github.com/JakeStanger/ironbar/assets/35699052/de32acca-2bf0-4c7b-bf0c-2213cd4aa32a)

**Comment by JakeStanger** [comment]
I think that's it yeah

**Comment by pinkcreeper100** [comment]
been trying to figure it out for a couple days lul

**Comment by pinkcreeper100** [comment]
hm, I just switched gtk theme and now the workspaces are flickering

**Comment by pinkcreeper100** [comment]
https://github.com/JakeStanger/ironbar/assets/35699052/580148c1-2a9b-4131-a963-a6a1d6c47431

**Comment by JakeStanger** [comment]
That looks related to the GTK theme. If you have issues with other themes, feel free to open another issue/discussion, but please keep this one on subject.

**Comment by JakeStanger** [comment]
Resolved by https://github.com/JakeStanger/ironbar/commit/cb2f9b0aaff1519516664ab04a3a195d29983b4e
