### ISSUE TITLE
Fails to compile when installing with ```cargo install ironbar```

### ISSUE THREAD

**Issue by TWB0109** [JakeStanger/ironbar#269]
**Describe the bug**
When installing through cargo install, everything compiles fine, but when it gets to compile hyprland v0.3.1 , it fails and spits the error down below.

```
error[E0599]: no variant or associated item named `__Nonexhaustive` found for enum `regex::Error` in the current scope
   --> /home/brandon/.cargo/registry/src/index.crates.io-6f17d22bba15001f/hyprland-0.3.1/src/event_listener/shared.rs:408:25
    |
408 |         Err(RegexError::__Nonexhaustive) => unreachable!(),
    |                         ^^^^^^^^^^^^^^^ variant or associated item not found in `Error`

error[E0599]: no variant or associated item named `__Nonexhaustive` found for enum `regex::Error` in the current scope
   --> /home/brandon/.cargo/registry/src/index.crates.io-6f17d22bba15001f/hyprland-0.3.1/src/event_listener/shared.rs:419:25
    |
419 |         Err(RegexError::__Nonexhaustive) => unreachable!(),
    |                         ^^^^^^^^^^^^^^^ variant or associated item not found in `Error`

For more information about this error, try `rustc --explain E0599`.
error: could not compile `hyprland` (lib) due to 2 previous errors
warning: build failed, waiting for other jobs to finish...
error: failed to compile `ironbar v0.12.1`, intermediate artifacts can be found at `/tmp/cargo-installh9aZfY`
``` 
**To Reproduce**
1. run cargo install ironbar
2. wait

**Expected behavior**
Complete compilation of hyprland and install. 

Also, after compiling from source, it worked just fine, could be a cargo issue, but I figured I'd ask here just in case.

**System information:**
 - Distro: OpenSUSE Tumbleweed
- Compositor: Hyprland
 - Ironbar version: 0.13.0

**Configuration**

**Additional context**
> Add any other context about the problem here.

**Screenshots**
![image](https://github.com/JakeStanger/ironbar/assets/53587182/740d3960-62ce-47aa-af32-c214c890de9c)

**Comment by yavko** [comment]
Yeah Hyprland 0.3.1 is broken, does ironbar still use it?

**Comment by yavko** [comment]
Yeah seems to be the case

**Comment by JakeStanger** [comment]
I've not updated it yet because there are breaking changes I need to deal with. I'll update as soon as I can now this is higher priority.

@yavko if that's the case, can you yank the version from crates.io please?

**Comment by yavko** [comment]
> I've not updated it yet because there are breaking changes I need to deal with. I'll update as soon as I can now this is higher priority.
> 
> @yavko if that's the case, can you yank the version from crates.io please?

Sure, it actually wasn't broken, but cuz regex updated, i ofc didn't make it use a specific version of it, so it broke :P

**Comment by yavko** [comment]
> > I've not updated it yet because there are breaking changes I need to deal with. I'll update as soon as I can now this is higher priority.
> > @yavko if that's the case, can you yank the version from crates.io please?
> 
> Sure, it actually wasn't broken, but cuz regex updated, i ofc didn't make it use a specific version of it, so it broke :P

yanked

**Comment by JakeStanger** [comment]
@TWB0109 the `cargo install` build will likely remain broken until next release, which I'm aiming to get out next week. For now, you can build [from source](https://github.com/JakeStanger/ironbar/wiki/compiling). 

I'm not sure about the specific build requirements for OpenSUSE but if you do go for it & need to install any packages, if you're able to let me know I can add instructions to the wiki
