### ISSUE TITLE
[Workspaces] Visible workspaces CSS selector

### ISSUE THREAD

**Issue by malicean** [JakeStanger/ironbar#282]
**Is your feature request related to a problem? Please describe.**
I'm migrating from Waybar and noticed that there's no CSS selector for visible workspaces. I use two monitors, but since I do all my work on my left monitor, workspaces buttons for my right monitor are never highlighted (active).

**Describe the solution you'd like**
A CSS selector such as `.workspaces .item.visible` which is active for workspace buttons whose workspaces are currently visible, including the active one.

**Describe alternatives you've considered**
After writing the previous section, I noticed that there's `.workspaces .item.inactive` ([implementation](https://github.com/JakeStanger/ironbar/blob/master/src/modules/workspaces.rs#L97)) from #147, but it doesn't do anything. Looking at the call sites, all 3 of them have the `inactive` parameter set to `false`, which would explain why. I think this is what the variable is supposed to represent, but there's no documentation aside from the comment in #90. I'll try to get it working for this purpose, but I figured I should post the issue regardless.

**Comment by malicean** [comment]
Ah, nevermind, I see that inactive is for favorited workspaces that don't exist.

**Comment by malicean** [comment]
I ended up getting it working, the code's on my fork. I realize discussion before writing is the convention, but this is a big QoL to me. If needed, I can adjust design.

**Comment by yavko** [comment]
> h, nevermind, I see that inactive is for favorited workspaces that don't exist.

yuh

**Comment by yavko** [comment]
> **Is your feature request related to a problem? Please describe.** I'm migrating from Waybar and noticed that there's no CSS selector for visible workspaces. I use two monitors, but since I do all my work on my left monitor, workspaces buttons for my right monitor are never highlighted (active).
> 
> **Describe the solution you'd like** A CSS selector such as `.workspaces .item.visible` which is active for workspace buttons whose workspaces are currently visible, including the active one.
> 
> **Describe alternatives you've considered** After writing the previous section, I noticed that there's `.workspaces .item.inactive` ([implementation](https://github.com/JakeStanger/ironbar/blob/master/src/modules/workspaces.rs#L97)) from #147, but it doesn't do anything. Looking at the call sites, all 3 of them have the `inactive` parameter set to `false`, which would explain why. I think this is what the variable is supposed to represent, but there's no documentation aside from the comment in #90. I'll try to get it working for this purpose, but I figured I should post the issue regardless.

If ur trying to get workspaces that exist, but aren't focused you could just use `:is(:not(.focused), :not(.inactive))` or something, ofc idk if this works in gtk css, but i hope so

**Comment by yavko** [comment]
> but there's no documentation aside from the comment 

That's my oopsie sorry, `.inactive` is for fake workspace that dont actually exist, but are in favorites list

**Comment by malicean** [comment]
> If ur trying to get workspaces that exist, but aren't focused you could just use `:is(:not(.focused), :not(.inactive))` or something, ofc idk if this works in gtk css, but i hope so

The problem isn't what exists but isn't focused, but what exists and is visible. I have 6-10 allocated to my right monitor (via Hyprland config), the rest to the left. Usually most of 6-10 exist, but only one is visible at a time. My left monitor is where I get work done, so 1-5 is almost always focused, leaving most of 6-10 existing but with no indicator as to which one I'm looking at

**Comment by JakeStanger** [comment]
> I ended up getting it working, the code's on my fork. I realize discussion before writing is the convention, but this is a big QoL to me. If needed, I can adjust design.

Agreed this is a good QoL addition & deffo makes sense to add it in. If you're able to open a PR, I'll review/merge when I can :)

I'll also look to get the docs updated in a sec to add that missing `.inactive` selector.
