### ISSUE TITLE
Support for listening variables

### ISSUE THREAD

**Issue by JustSimplyKyle** [JakeStanger/ironbar#30]
https://github.com/JakeStanger/ironbar/wiki/script
Currently ironbar only supports reading from stdout
I wish it's possible to do this instead(I'm from `eww`)
![image](https://user-images.githubusercontent.com/68589851/198594556-59fd1c0d-22e2-4749-848d-bfcf1f4819b1.png)

**Comment by JakeStanger** [comment]
I can definitely see the value in this & I reckon it should be possible without too much difficulty.
