### ISSUE TITLE
Respect interval in show_if or add show_if_interval

### ISSUE THREAD

**Issue by kepi** [JakeStanger/ironbar#335]
**Is your feature request related to a problem? Please describe.**

While trying to handle `checkupdates` script as mentioned in #333 I tried to add `show_if` with simple `checkupdates`, as it returns 0 when there are some updates. I have `interval` for `script` set to 30 minutes.

I would like whole updates module to be hidden when there are no updates.

Problem is, that `check_if` ignores `interval` and runs constantly.

**Describe the solution you'd like**

I would like for `show_if` to honor `interval`, or add something like `show_if_interval`.

**Describe alternatives you've considered**

With `script` module, I can simply set some ironvar when there are updates. It might be even more efficitent, but it seems to me that I have to offload a lot of work to scripts, which seems little fragile to me.

**Additional context**

Btw. all three issues are just ideas, feel free to reject them if you think it is better to use little heavier scripts leveraging ironvars feature.

**Comment by JakeStanger** [comment]
I think what you're asking for can be done. The important thing to keep in mind here is that `show_if` is effectively its own script, independent of the module (when not using an ironvar). This means you can use [shorthand script syntax](https://github.com/JakeStanger/ironbar/wiki/scripts#shorthand-string) to set the module and interval.

Using your example from #333:

````yaml
- type: 'script'
  cmd: 'checkupdates | wc -l | xargs -n1 echo "󰏕"'
  interval: 1800000
  show_if: 'poll:1800000:checkupdates'

**Comment by kepi** [comment]
I didn't realize that I can use shorthand form in `show_if`. That is definitelly sufficient.

Thanks!
