### ISSUE TITLE
Support for tooltips in various modules

### ISSUE THREAD

**Issue by JustSimplyKyle** [JakeStanger/ironbar#36]
Currently there is no way of customizing the tooltip(e.g. when you hover above the modules, something will pop-up)
I think most of the modules can add this functionality, except for `sys-info`?
I'm not sure how will the syntax be for `sys-info` tho 
https://github.com/JakeStanger/ironbar/wiki/sys-info

**Comment by JakeStanger** [comment]
I think this would pair nicely with the `show-if` we discussed in #34 as a 'common' option available on all modules. I've got a few more I've been wanting to add (on click, on right click, that sort of thing) so this might be a good chance to add a system for all of those.

For `sys-info`, the tooltip would just show on the outer container. If you wanted different tooltips for different sections, you could add multiple instances of the widget.

**Comment by JakeStanger** [comment]
Going to reopen this actually. The update just pushed adds a `tooltip` config option you can set on each module, but it only allows static text at the moment. I think that's going to need support for dynamic text through scripts to really be useful.

**Comment by JakeStanger** [comment]
Tooltips live with ability to embed scripts: https://github.com/JakeStanger/ironbar/wiki/scripts#embedding
