### ISSUE TITLE
Startup on Hyprland

### ISSUE THREAD

**Issue by steveslatky** [JakeStanger/ironbar#361]
I am not sure if I am missing something but I am having trouble getting it to start on startup with hyprland. I have `exec-once = ironbar ` in my config. It doesn't start and there is nothing in the log file. Using `hyprctl dispatch exec ironbar` it doesn't start either. The only way I have been able to successfully start it is with just calling the binary in a terminal.

**Comment by yavko** [comment]
> I am not sure if I am missing something but I am having trouble getting it to start on startup with hyprland. I have `exec-once = ironbar ` in my config. It doesn't start and there is nothing in the log file. Using `hyprctl dispatch exec ironbar` it doesn't start either. The only way I have been able to successfully start it is with just calling the binary in a terminal.

If you installed with cargo, it might not be in path? That's all I can think of.

**Comment by JakeStanger** [comment]
It may be worth checking the error log in case anything goes in there (for both Hyprland or Ironbar), otherwise yeah a PATH configuration issue sounds plausible.

**Comment by steveslatky** [comment]
That was it, thanks. It was installed bar cargo and in the cargo path. Moving to /usr/bin/ solved it.

**Comment by yavko** [comment]
> That was it, thanks. It was installed bar cargo and in the cargo path. Moving to /usr/bin/ solved it.

Then you can't easily update tho

**Comment by JakeStanger** [comment]
Yeah I wouldn't recommend moving it. Instead look into adding ~/.cargo/bin to your PATH

**Comment by JakeStanger** [comment]
Closing as resolved - if you have any more issues let me know.
