### ISSUE TITLE
Workspaces not closing/switching properly on Hyprland

### ISSUE THREAD

**Issue by JakeStanger** [JakeStanger/ironbar#381]
**Describe the bug**
Workspaces no longer seem to be correctly removed, instead duplicating and showing as in focus still. This is known to affect Hyprland, has not been tested on Sway.

**To Reproduce**
1. Open a workspace.
2. Close the workspace and switch to another, or move the current workspace to another monitor.
3. Observe the workspace does not correctly disappear. 

**Expected behavior**
Workspaces should be correctly removed when moved/closed.

**System information:**
 - Distro: Arch Linux
- Compositor: Hyprland (git)
 - Ironbar version: 1.14.0-pre ([29eeefb](https://github.com/JakeStanger/ironbar/commit/29eeefbd24a7741db48889ba951bc7992edcd7ad))

**Configuration**

<details><summary>Config</summary>

```corn
  $workspaces = {
        type = "workspaces"
        all_monitors = false
        name_map = {
            1 = "<U+F066F>"
            2 = "<U+F268>"
            3 = "<U+F120>"
            4 = "<U+F121>"
            5 = "<U+F11B>"
            Games = "<U+F11B>"
            Code = "<U+F121>"
        }
    }
```
</details>

**Screenshots**
![image](https://github.com/JakeStanger/ironbar/assets/5057870/93e85709-108a-4e65-b702-29a6de426e7e)

**Comment by yavko** [comment]
Maybe it has to do with fake workspaces that were added with favorite workspaces

**Comment by JakeStanger** [comment]
I don't think so, as I'm not using those options myself. It's also very consistently broken and I've only ran into it recently after some refactors - think I'd definitely have hit it before. There is a chance a Hyprland commit caused it, but haven't investigated that yet.
