### ISSUE TITLE
[BUG] Pango parses ironvars inside Dynamic String fields incorrectly

### ISSUE THREAD

**Issue by izelnakri** [JakeStanger/ironbar#418]
Given: 

```
{
  "type": "label",
  "label": "<span color='#battery-color'>#battery-percent</span>"
}
```

I get this runtime error, even when `ironvar_defaults` defined:

`(ironbar:445544): Gtk-WARNING **: 16:34:18.280: Failed to set text '<span color='' from markup due to error parsing markup: Error on line 1 char 31: Document ended unexpectedly while inside an attribute value`

Ironbar version: `v0.14.0`

**Comment by JakeStanger** [comment]
Fixed an issue where the dynamic string parser was being too greedy, and a separate issue where it'd initialize with an empty string causing the warning. Cheers for reporting
