### ISSUE TITLE
Wider pango markup support

### ISSUE THREAD

**Issue by s0ulslack** [JakeStanger/ironbar#443]
I see we can use pango markup with clock and custom modules but that looks like thats it? I'm trying to use it with a label or script module tooltip with no luck

Loving the bar, adapting all my waybar stuff!

**Comment by JakeStanger** [comment]
The `label`, `script` and `upower` modules also support markup in their formatting, but you're right that tooltips do not currently support this.

I'm happy to enable markup in more places, as I'm not aware of any drawbacks of doing so. There's probably few, if any, places where it makes sense to have it off, so it probably makes sense to do a big sweep at some point.
