### ISSUE TITLE
Tray module: missing or different sized icons

### ISSUE THREAD

**Issue by undesarrolladormas** [JakeStanger/ironbar#452]
**Describe the bug**
Some tray icons are not displayed and others have different sizes.

**To Reproduce**
1. Open Ironbar with the tray module
2. Open Discord
3. Open the GUI for asusctl  
4. Open KeepassXC with the option to show a system tray icon
5. See error

**Expected behavior**
> All icons should be the same size
> All icons should be visible

**System information:**
- Distro: Arch Linux
- Compositor: Hyprland 0.35.0-2
- Ironbar version: 0.15.0-pre

**Additional context**
In the screenshot, the missing icon corresponds to Discord
The largest icon corresponds to asusctl
The KeepassXC app icon never appears, it doesn't even show an empty space, like the Discord icon does

**Screenshots**
![image](https://github.com/JakeStanger/ironbar/assets/46760543/a10ebe76-78cb-49a2-a2d0-3e944c89a3e8)

**Comment by JakeStanger** [comment]
Thanks for reporting. Looks like there's still a good way to go before the tray is really there.

**Comment by JakeStanger** [comment]
I've just opened a draft PR that *may* resolve the incorrectly sized issues. I'm not easily able to replicate the issues myself, so are you able to test the above PR and see if it helps at all please?

The PR also includes a new `icon_size` setting for the tray module so you can control that if it's too large/small by default.

Issues with icons not rendering, or items not showing at all run deeper and are going to take a bit longer to resolve.

**Comment by chmanie** [comment]
Adding the icon_size was a secret wish of mine, thanks for that (the bigger icons are much prettier oftentimes). Cheers 💖

**Comment by JakeStanger** [comment]
@undesarrolladormas hey have you been able to test the PR to see if this resolves the issue?

**Comment by undesarrolladormas** [comment]
I've been testing a bit, the new `icon_size` setting doesn't prevent that app's icon from getting bigger.
e.g. with `icon_size: 25` 
![image](https://github.com/JakeStanger/ironbar/assets/46760543/713bb306-c236-4854-8e97-522ba30f5c81)

But it allows to make it bigger
e.g. with `icon_size: 80`
![image](https://github.com/JakeStanger/ironbar/assets/46760543/71a64f5e-fa44-4c9a-9ba6-9af6d4e856ad)

Looking through the project a bit, it looks like they only use 512x512 icons for the tray. Would it have anything to do with that?

**Comment by JakeStanger** [comment]
It could be although I don't get why. I request the image is scaled down to size so being too large shouldn't matter.

The only thing I can think of is that the image isn't actually square. Are you able to double check it's 512x512 please?

If you could also send the image file please, I might be able to fudge something to be able to test it myself.

**Comment by undesarrolladormas** [comment]
You can get the icons from their repository [here](https://gitlab.com/asus-linux/asusctl/-/tree/main/data/icons)

Checking one of the icons, it is indeed a 512x512 image
```
$ identify -verbose asus_notif_blue.png
Image:
  Filename: asus_notif_blue.png
  Permissions: rw-r--r--
  Format: PNG (Portable Network Graphics)
  Mime type: image/png
  Class: DirectClass
  Geometry: 512x512+0+0
  Resolution: 28.35x28.35
  Print size: 18.06x18.06
  ...
```

**Comment by JakeStanger** [comment]
Weird, I'm trying that image file directly and it respects `icon_size` as expected, both smaller and larger. The same goes for the SVGs in the repo so it's not that.

Could you share your module config and related styles please, and I'll try those?

**Comment by JakeStanger** [comment]
I have just merged a PR that completely rewrites the tray client code. I'm hoping that will resolve all of the issues you have been experiencing (probably except Discord, which seems to have a bugged tray implementation in its side). Can you let me know how the latest master commit works for you please?

**Comment by JakeStanger** [comment]
Going to close this as I've not heard back, and since the client code has been entirely written I would expect any outstanding issues to now be outdated. If you still have issues, let me know and we can re-open and go from there.
