### ISSUE TITLE
Error log file grows indefinitely & can result in very large files

### ISSUE THREAD

**Issue by JakeStanger** [JakeStanger/ironbar#453]
### Discussed in https://github.com/JakeStanger/ironbar/discussions/451

<div type='discussions-op-text'>
<b>how the hell did the error log get up to 282.6 GiB</b><br>
<sup>Originally posted by **pinkcreeper100** February 13, 2024</sup><br>
https://akko.wtf/notice/AeqeKmpXN9P9D6N54i

it was full of broken pipe errors</div>

**Comment by pinkcreeper100** [comment]
@JakeStanger 
the original cause is still occurring though

```
2024-03-01T07:36:14.772167Z ERROR ironbar::clients::wayland: 
   0: Failed to dispatch pending wayland events
   1: other error during loop operation
   2: underlying IO error
   3: Broken pipe (os error 32)

Location:
   src/clients/wayland/mod.rs:305

Backtrace omitted. Run with RUST_BACKTRACE=1 environment variable to display it.
Run with RUST_BACKTRACE=full to include source snippets.
```

**Comment by JakeStanger** [comment]
Please open a proper issue with more detail and I can investigate

**Comment by ToxicMushroom** [comment]
This may be related to incorrectly launching ironbar #632 ? 
```
Every 2.0s: ls -al .local/share/ironbar/ironbar.2024-06-12.log             arch: Wed Jun 12 02:44:42 2024

-rw-r--r-- 1 merlijn merlijn 24266396770 Jun 12 02:44 .local/share/ironbar/ironbar.2024-06-12.log
```
700MB in about 1 minute
```
Every 2.0s: ls -al .local/share/ironbar/ironbar.2024-06-12.log             arch: Wed Jun 12 02:45:50 2024

-rw-r--r-- 1 merlijn merlijn 24926470338 Jun 12 02:45 .local/share/ironbar/ironbar.2024-06-12.log
```

Apparently I have many ironbar processes running
```
130 merlijn@arch ~ % pgrep ironbar
2809
188396
374343
374381
399618
399683
```

Every time I reload sway it creates another ironbar that is just producing these errors in a loop x)
![image](https://github.com/JakeStanger/ironbar/assets/32853531/10d4e8b1-bea1-464c-bdb1-3d9b4d6165ab)

I think ideally ironbar should detect that it is already running and not try to do whatever it is doing right now ? Or maybe there is a way to handle sway reload better.

**Comment by ToxicMushroom** [comment]
Might be useful to know that it's the old process that starts freaking out, not the newly created one after reload

**Comment by JakeStanger** [comment]
> I think ideally ironbar should detect that it is already running and not try to do whatever it is doing right now ? Or maybe there is a way to handle sway reload better.

It's *supposed* to exit if another instance is already running, so this is a separate bug. The additional instances shouldn't get any further than setting up a Wayland client though, so that likely wouldn't explain the config file sizes.
