### ISSUE TITLE
Provide binaries for every release in Github releases

### ISSUE THREAD

**Issue by VarLad** [JakeStanger/ironbar#490]
Providing statically compiled binaries would make it much easier for users to simply try the software in the first place.
Since it has a lot of dependencies, compiling it from scratch is a pain on older systems. 
You might point towards distro packaging but having binaries helps with some immutable distros where packages are not feasible.

**Comment by yavko** [comment]
This shouldn't be too hard since ironbar is built on every commit, the only difference would be setting a build artifact so you could download from every GH action, and maybe also an action that builds in release on a new tag

**Comment by slowsage** [comment]
This may help (was rejected since I did not think through targets/environments etc.): #227

**Comment by JakeStanger** [comment]
I think providing binaries for each tagged release is sensible. I won't add them to the CI build on every push because that will generate a lot of noise (plus if you're following Git you're surely happy to build from source, right? :p)

The main questions I guess is how and in what format(s). Supporting x86_64 and (possibly) ARM64 sounds like a good idea to me. 

What considerations are there around different C stdlibs (GNU, Musl) or anything like that? I'm not too clued up there and see there was some reference to those in the above PR.

**Comment by slowsage** [comment]
I suggest we avoid musl and stick to gnu based on ironbar's multi-threading and musl's memory allocator having perf issues: https://github.com/nextstrain/nextclade/issues/1338.

I can try https://github.com/marketplace/actions/build-rust-projects-with-cross and get back if this makes sense for `aarch64-unknown-linux-gnu` and `x86_64-unknown-linux-gnu`.

**Comment by yavko** [comment]
> I suggest we avoid musl and stick to gnu based on ironbar's multi-threading and musl's memory allocator having perf issues: [nextstrain/nextclade#1338](https://github.com/nextstrain/nextclade/issues/1338).
> 
> I can try [github.com/marketplace/actions/build-rust-projects-with-cross](https://github.com/marketplace/actions/build-rust-projects-with-cross) and get back if this makes sense for `aarch64-unknown-linux-gnu` and `x86_64-unknown-linux-gnu`.

Just cuz its slower, shouldn't be a reason to prevent users from using it, tho. Also, as the issue mentioned, it could be made better with the use of a different allocator like jemalloc, which is pretty easy with rust.

**Comment by JakeStanger** [comment]
Let's stick to GNU for now in that case. We can revisit musl separately if there's demand for it, and handle the perf/allocator issue then.

Feel free to try any actions or work flow changes out and see how it goes.

**Comment by slowsage** [comment]
Tested #504 on my repo. (Re-forked later to clean up tags).
Decided not to change the existing yml files to keep this separate and avoid dependencies. The setup is pretty quick till cross gets the docker images anyway.

**Comment by slowsage** [comment]
Found a workaround - will add openssl vendored just for the binary.yml till the cross-rs image gets updated. This leaves Cargo.toml as is and passes garnix ci build checks.
