### ISSUE TITLE
[Question] Custom module and space?

### ISSUE THREAD

**Issue by bluebyt** [JakeStanger/ironbar#495]
I have a custom module that display the weather, but I am wondering why there is a big space between icon and temperature?
 
Script:
#!/bin/bash
curl wttr.in/Montreal?format="%c%t\n"

In Ironbar:
![20240312_185419](https://github.com/JakeStanger/ironbar/assets/18442224/764754cf-a78b-4b42-a26e-a1ee6bcde195)

In the terminal:
![20240312_185335](https://github.com/JakeStanger/ironbar/assets/18442224/bf144804-db5b-4574-8fc7-f5ecb016bf2f)

Script module:
    $weather = {
        name = "weather"
        type = "script"
        mode = "poll"
        interval = 600000
        cmd = "~/.config/ironbar/scripts/weather"
   }

**Comment by JakeStanger** [comment]
Looks like wttr.in adds some spaces between the two formatting tokens automatically, which render wider with your Ironbar font than your terminal one.

I'm not sure if there's anything you could do with CSS. The easiest fix is probably just to pipe the output of curl into something that strips out the additional space(s).

**Comment by bluebyt** [comment]
Good idea I solved the problem with the sed command;

#!/bin/bash
curl -s wttr.in/Montreal?format="%c%t\n" | sed 's/ //'

![20240312_202524](https://github.com/JakeStanger/ironbar/assets/18442224/61ac7032-51e8-4c92-a599-d070e1104f9c)
