### ISSUE TITLE
Task Switcher

### ISSUE THREAD

**Issue by Ithvr** [JakeStanger/ironbar#498]
**Describe the solution you'd like**
Would be be possible to add a task switcher (alt+tab) to Ironbar?
Most window managers don't have it (or a sub optimal) implementation, and it would be nice to "carry" the task switcher setup when/if I move to another WM instead of finding another VM specific solution.
I wouldn't be surprised if this is out of scope.

**Describe alternatives you've considered**
The sfwbar panel actually implements a task viewer that might serve as an insperasion

**Comment by JakeStanger** [comment]
I'd consider a task switcher out of scope of Ironbar. I want to keep Ironbar to being just a bar, and that'd be a different project.

**Comment by yavko** [comment]
If ur on hyprland there are plugins for this
