### ISSUE TITLE
Usage of symbolic icons from the system icon theme

### ISSUE THREAD

**Issue by pinkcreeper100** [JakeStanger/ironbar#51]
**Is your feature request related to a problem? Please describe.**
> having to use a nerd font for icons

**Describe the solution you'd like**
> allow for using the icons from the system icon theme for modules/widgets

**Comment by JakeStanger** [comment]
This is a little complex as icons are just images, so have to be added as a separate GTK widget. I could potentially add support for:

- Adding images/icons at the start/end of widgets as some common config option (like the tooltip etc)
- A standalone image module
- Images in the custom module

Being able to just add icons anywhere in place of Nerd Font icons I won't do as it adds quite a lot of complexity.

**Comment by pinkcreeper100** [comment]
I think the first option would be best

**Comment by pinkcreeper100** [comment]
I don't really need them to be in any specific position

**Comment by JakeStanger** [comment]
The above PR will get this sorted. I've not  added the prefixes/suffixes since `custom` will cover that ,but you can now use images in the `custom` module, and inside `workspace.name_map`  and `music.icons`:

```corn
let {
  $workspaces = {
    type = "workspaces"
    name_map = {
      1 = "icon:firefox"
    }
  }

  $image = {
    type = "custom"
    //                               \/ http(s) also supported
    bar = [ { type = "image" src = "file:///path/to/image.jpg" size = 32 }  ]
  }
} in {
  icon_theme = "Paper"

  left = [ $workspaces ]  right = [ $image ]
}
```
