### ISSUE TITLE
system tray menus do not work when opened with right click

### ISSUE THREAD

**Issue by michaelBelsanti** [JakeStanger/ironbar#513]
**Describe the bug**
Both right clicking and left clicking opens the menu for items in the system tray, but if you open the menu with a right click, the buttons do not work.

**To Reproduce**
1. Right click on icon in system tray
2. Click a menu option
3. It doesn't work

**System information:**
 - Distro: NixOS Unstable
- Compositor: Hyprland
 - Ironbar version: 0.15.0-pre (master)

**Configuration**
https://github.com/michaelBelsanti/nixconfig/blob/main/modules/nixos/desktops/hyprland/ironbar.nix

**Comment by JakeStanger** [comment]
It seems the default behaviour of the GTK 'activate' signal is that it is only called when you click a menu item with the same button you click to open the menu. I've switched it to use a button click signal that seems more consistent.

**Comment by ToxicMushroom** [comment]
Eh I still see this behavior
```
Sway 1.9
Ironbar 1.16.0-pre
```

**Comment by JakeStanger** [comment]
Sorry, I didn't mean to close

**Comment by JakeStanger** [comment]
Re-opened, will investigate.

**Comment by JakeStanger** [comment]
lol im so stupid

**Comment by JakeStanger** [comment]
There's two signals - I updated one of them but not the other.

**Comment by ToxicMushroom** [comment]
ty :)
