### ISSUE TITLE
dlauncher and ulauncher oneclick modules

### ISSUE THREAD

**Issue by daktras420** [JakeStanger/ironbar#519]
using the oneclick command i am hoping to integrate ulauncher and its extensions the link below explains it in detail
https://docs.ulauncher.io/en/stable/extensions/intro.html
https://ext.ulauncher.io/-/github-lighttigerxiv-ulauncher-session-manager
https://ext.ulauncher.io/-/github-melianmiko-ulauncher-nmcli
https://ext.ulauncher.io/-/github-iboyperson-ulauncher-system
are some examples i think are very usable there is a bunch more
dlauncher is based off ulauncher and would be again as a one click  great for an program menu aka start or applications menu
any help or ideas in setting this up of course would be very appreciated

**Comment by JakeStanger** [comment]
This to me sounds like it's well suited to the `custom` module rather than a native module. It should be a very easy config if all you want is a button that executes a command.

**Comment by daktras420** [comment]
That's what I was thinking. I figured id work on it today.

**Comment by JakeStanger** [comment]
Sure, if you put something together feel free open a PR to add it as example to the wiki or post it as a show-and-tell discussion.

I'll close this since there's no development action to be taken.
