### ISSUE TITLE
When setting "features" through HomeManager config in Nix, cargo throws an error

### ISSUE THREAD

**Issue by tukanoidd** [JakeStanger/ironbar#520]
**Describe the bug**
When I set the "features" option in `programs.ironbar.features`, I get a build error:
```
last 10 log lines:
> cargo --no-default-features -F "cli,http,config+json,clipboard,clock,focused,launcher,music+all,notification,sys_info,tray,upower,volume" build $cargo_release -j "$NIX_BUILD_CORES" --message-format=$cargo_message_format
> error: unexpected argument '--no-default-features' found
>
>   tip: 'build --no-default-features' exists
>
> Usage: cargo [OPTIONS] [COMMAND]
>        cargo [OPTIONS] -Zscript <MANIFEST_RS> [ARGS]...
>
> For more information, try '--help'.
> [naersk] cargo returned with exit code 1, exiting
```

**To Reproduce**
1. Set `programs.ironbar.features` to something else than `[]`
2. Try rebuilding the system
3. Get the error

**Expected behavior**
Project builds.

**System information:**
 - Distro: NixOS unstable
- Compositor: Hyprland/Trying to make it work in niri as I'm assuming, workspace specific code makes it not show up (maybe?)
 - Ironbar version: 0.15.0-pre (dictated by the flake)

**Configuration**
> N/A

**Additional Context**
I made sure to run nix flake update and try to build again in case the bug was fixed, but it wasn't.

I also took a look into `default.nix` and all does seem good, so I'm not sure if it's the ironbar flake or naersk issue, so sorry if this issue is not relevant here. 

**Screenshots**
![image](https://github.com/JakeStanger/ironbar/assets/45230259/e99c30aa-d79a-4df5-8cc3-747675b54dda)

**Comment by JakeStanger** [comment]
I think this is because the naersk builder was using the wrong option for passing build flags. I've amended that in the PR above - is this something you're able to confirm resolves the issue please?

**Comment by tukanoidd** [comment]
Will try, although I'm not sure how to use the PR version as the input, haven't done it before, need to check first, will lyk as soon as I get some results

**Comment by tukanoidd** [comment]
Ok, found it, and the build does seem to go through, thanks for the fix!

**Comment by JakeStanger** [comment]
Perfect, thanks for testing that. Merged so you can target master now.

**Comment by tukanoidd** [comment]
Thanks!
