### ISSUE TITLE
exiting session causes broken pipe error spam

### ISSUE THREAD

**Issue by pinkcreeper100** [JakeStanger/ironbar#528]
**Describe the bug**
when i exit the session, the logs are spammed with broken pipe errors

**To Reproduce**
1. launch your wayland compositor
2. exit the session
3. check the latest log

**Expected behavior**
ironbar exits cleanly with the session

**System information:**
 - Distro: NixOS
- Compositor: Sway
 - Ironbar version: 0.15.0-pre (flake input last updated at: 1711718149)

**Screenshots**

![image](https://github.com/JakeStanger/ironbar/assets/35699052/67706a15-ac8f-46b5-add4-63b7a179199d)

**Comment by JakeStanger** [comment]
How is Ironbar started? Are you using a systemd service?

The errors make sense as Ironbar is staying open once your compositor closes for some reason, which obviously isn't going to work. The question is how we ensure it closes.

**Comment by pinkcreeper100** [comment]
ah, I'm starting it inside the sway config
https://git.gay/pinkcreeper100/nix-config/src/branch/main/modules/home/desktop/sway/default.nix#L158

**Comment by pinkcreeper100** [comment]
that'd make sense

**Comment by JakeStanger** [comment]
What if you set it as a bar rather than a startup command? Hopefully sway would handle shutting it down then. If not I'll have to change the wayland client logic to exit on error.

**Comment by pinkcreeper100** [comment]
when i looked in btop, there were two ironbar processes, so i've removed it from the `startup` and will check if it still works

**Comment by pinkcreeper100** [comment]
the systemd unit works

**Comment by JakeStanger** [comment]
What systemd unit? Define 'works'. Did you test my suggestions?

Pleae give me something to go on here.

**Comment by pinkcreeper100** [comment]
I removed ironbar from the startup section in my sway config, and just using the systemd unit provided by the module, i no longer seem to encounter the error

**Comment by JakeStanger** [comment]
In that case I'll close this issue. Any further issues let me know and we can reopen

**Comment by pinkcreeper100** [comment]
> If not I'll have to change the wayland client logic to exit on error.

it may still be a good idea to do this, as there may be users who don't use the systemd unit, or just aren't using systemd at all

**Comment by yavko** [comment]
> I removed ironbar from the startup section in my sway config, and just using the systemd unit provided by the nix module, i no longer seem to encounter the error

Glad my code works
