### ISSUE TITLE
Multiple bar across all monitors

### ISSUE THREAD

**Issue by huyufeifei** [JakeStanger/ironbar#537]
I have two monitors and I want to show two bars (top and bottom) in each monitor. Contents of bars in the same position but different monitor should be the same(e.g. top bar in monitor-1 and top bar in monitor-2).

I know there is a way to configure it, as below:
```json
{
  "monitors": {
    "monitor-1": [
      { "position": "top", ... },
      { "position": "bottom", ... }
    ],
    "monitor-2": [
      { "position": "top", ... },
      { "position": "bottom", ... }
    ]
  }
}
```
but this is not very graceful, since I need to repeat the same object multiple times.

I want to know whether there is a way to set a "default" bars config for every monitors which supports multiple bars. Current way seems only support one bar as default.

**Comment by JakeStanger** [comment]
Hey, there is no way to do this with JSON or TOML. YAML [possibly](https://en.wikipedia.org/wiki/YAML#Advanced_components) has some templating features built in, although I've never tested if the Rust implementation includes them.

This can however be easily done with the [Corn](https://cornlang.dev/) format and its inputs mechanism:

```corn
let {
  $bar = { start = [] center = [] end = [] }

  $bars = [
    { position = "top" ..$bar } 
    { position = "bottom" ..$bar } 
  ]
} in {
  monitors.monitor-1 = $bars
  monitors.monitor-2 = $bars
}

**Comment by huyufeifei** [comment]
Thanks for reply! It works fine.
