### ISSUE TITLE
Feature: JSON Schema for Config

### ISSUE THREAD

**Issue by LeSnake04** [JakeStanger/ironbar#541]
**Is your feature request related to a problem? Please describe.**
Configuration files currently can only be checked for syntax errors with taplo 

**Describe the solution you'd like**
Add an official syntax to the json schema store: https://taplo.tamasfe.dev/configuration/developing-schemas.html

**Describe alternatives you've considered**
None

**Additional context**
Pushing the json schema might also allow more lsps to check the config.

**Comment by yavko** [comment]
Yaml also has a schema, and maybe others do too

**Comment by LeSnake04** [comment]
Taplo is a toml lsp but it uses json schemas for lints, so json might be enough

**Comment by LeSnake04** [comment]
Im not 100% sure its possible to filter for ironbar/config.toml though. I couldnt find a json schema filtering by parent folder so far

**Comment by yavko** [comment]
Found a library for this https://graham.cool/schemars/

**Comment by JakeStanger** [comment]
Happy to add this, hopefully it should be a relatively straightforward build step to produce and export the schema.

> Taplo is a toml lsp but it uses json schemas to define lints, so json might be enough

Yes I'm pretty sure the other formats just adopted the JSON schema format, so that should tick all the boxes. Corn may or may not [eventually](https://github.com/corn-config/corn/issues/11) receive support too.

**Comment by JakeStanger** [comment]
I'm now generating and hosting schemas, meaning you can now add

```json
"$schema": "https://f.jstanger.dev/github/ironbar/schema.json",
```

to your JSON/YAML config to follow master. 

For tagged releases, starting with 0.16.0 when that releases, you will be able to use `https://f.jstanger.dev/github/ironbar/schema-v0.16.0.json`.
