### ISSUE TITLE
Icons Missing From Bar

### ISSUE THREAD

**Issue by SerraPi** [JakeStanger/ironbar#558]
The icons are missing from the example bar.

Noto Nerd Fonts from here [https://www.nerdfonts.com/font-downloads](https://www.nerdfonts.com/font-downloads)

will fix this issue

**Comment by JakeStanger** [comment]
The example styles also reference a nerd font, so yes you would need it to use the example. 

I'll add a note in the documentation somewhere to make this more apparent.
