### ISSUE TITLE
Cargo error when insalling Ironbar from the AUR

### ISSUE THREAD

**Issue by ForgotMyPasswd** [JakeStanger/ironbar#569]
**Describe the bug**
When I try to install ironbar-git from the AUR, iI get this error when building the package:
`error: the lock file /home/fahmed/.cache/yay/ironbar-git/src/ironbar/Cargo.lock needs to be updated but --locked was passed to prevent this`

**To Reproduce**
1. Install ironbar-git from AUR
4. Once dependencies are set up and the buid process starts, the error should appear

**Expected behavior**
Ironbar to compile properly and to prompt me to install it

**System information:**
 - Distro: Arch Linux
- Compositor: Hyprland
 - Ironbar version: 0.15.

**Comment by JakeStanger** [comment]
Sounds like an issue brought about by a dep update yesterday. Cloning and building locally should update the lockfile to check in - I should be able to do this tonight if nobody beats me to it :)
