### ISSUE TITLE
workspaces increase exponentially in length

### ISSUE THREAD

**Issue by pinkcreeper100** [JakeStanger/ironbar#574]
**Describe the bug**
> workspaces get longer when you switch between them

**To Reproduce**
1. switch to an empty workspace
2. switch back
3. repeat (and with other workspaces)

**Expected behavior**
> The text from the empty workspaces disappear when they are not focused and are empty

**System information:**
 - Distro: NixOS unstable (with lix)
- Compositor: sway
 - Ironbar version: 4695279d6927d05b6d3ed5a930e53f04d797c379

**Configuration**
> Share your bar configuration and stylesheet as applicable:

https://git.gay/pinkcreeper100/nix-config/src/branch/main/modules/home/desktop/ironbar

**Screenshots**

https://github.com/JakeStanger/ironbar/assets/35699052/d5bbb275-9847-43b7-81bd-36c9cfde00e2

**Comment by JakeStanger** [comment]
This was a regression due to changes made for Hyprland recently, and me not testing those changes on Sway properly. Lesson learned, apologies, fix landing in a few mins.
