### ISSUE TITLE
Ghost Icons in launcher after reloading

### ISSUE THREAD

**Issue by ForgotMyPasswd** [JakeStanger/ironbar#585]
**Describe the bug**
When I close a program, it disappears from the launcher as expected. However when I reload the bar, or if the bar is loaded in again on a secondary monitor, 'ghost icons' appear of every program I had opened since running the bar which usually means every programs I've used in a given Hyprland session. 

https://github.com/JakeStanger/ironbar/assets/96489361/5e45f0b4-bf3e-4fdd-bf82-a3eab3b4ac20

**To Reproduce**
1. Run ironbar
2. Open any program
3. Close the program'
4. Reload ironbar, a ghost icon of that closed program should appear

**System information:**
 - Distro: Arch Linux
- Compositor: Hyprland-git
 - Ironbar version: Git version

[Debug log](https://github.com/JakeStanger/ironbar/files/15283075/ironbar.2024-05-11.log)

**Comment by JakeStanger** [comment]
How strange. I can't see any reason for that to happen, and I've just given it a go myself and have not been able to replicate it. 

Are you able to re-produce but ensure that `IRONBAR_LOG=debug` (and `IRONBAR_FILE_LOG=debug` if uploading the log file) are set, and re-share the logs please?

**Comment by ForgotMyPasswd** [comment]
Sorry, I forgot to set IRONBAR_LOG to debug alongside IRONBAR_FILE_LOG I think.
[Here](https://github.com/JakeStanger/ironbar/files/15284338/ironbar.2024-05-11.log) are the debug logs.

**Comment by JakeStanger** [comment]
I have just hit this myself on the latest commit. Thanks for the logs, I'll look at this as soon as I can in the next few days.

**Comment by JakeStanger** [comment]
No idea how nobody's come across this one before, as the code hasn't been touched in months. Update landing in a few mins
