### ISSUE TITLE
[Launcher] Favorite apps stay in focused state when closed in Hyprland v0.40.0

### ISSUE THREAD

**Issue by donovanglover** [JakeStanger/ironbar#603]
**Describe the bug**
Favorite apps seem to stay in a focused state after closing them.

**To Reproduce**
1. Have favorite apps
2. Open one of them
3. Close the same app
4. Will appear as focused in the bar until restarted

**Expected behavior**
Should function similar to Hyprland v0.39.x and Ironbar 0.14.x

**System information:**
 - Distro: `Linux nixos 6.6.31 #1-NixOS SMP PREEMPT_DYNAMIC Fri May 17 10:02:40 UTC 2024 x86_64 GNU/Linux`
- Compositor: Hyprland 0.40.0-unstable-2024-05-12
 - Ironbar version: Tried 0.15.1 and latest commit https://github.com/JakeStanger/ironbar/commit/4ad4b0e070cc4e271251763db7210e70857d68ca

**Configuration**
https://github.com/donovanglover/nix-config/blob/50d788ab4d79d5896c4a046c6242b49b5ea5db08/home/ironbar.nix

**Additional context**
May have not occurred with Hyprland v0.39.x and Ironbar 0.15.1. Doesn't occur with non-favorite apps

**Comment by ClaireNeveu** [comment]
I've noticed that Krita stays in the bar when closed whether or not it's in the favorite list.

**Comment by JakeStanger** [comment]
The bug with favourites I can replicate, hopefully that should be a quick fix. 

The krita problem I'm not able to reproduce. @ClaireNeveu if you're hitting that consistenty would you mind opening a separate issue with debug logs please, and we can try and track that one down.
