### ISSUE TITLE
[Launcher] Windows open on out-of-focus workspace in Hyprland v0.40.0

### ISSUE THREAD

**Issue by donovanglover** [JakeStanger/ironbar#604]
**Describe the bug**
Ironbar will occasionally open new windows on a different workspace than the focused one in Hyprland v0.40.0

**To Reproduce**
1. Open a favorite app on the launcher
2. Occasionally starts on a workspace with a higher id. Might be easier to reproduce when starting Hyprland for the first time and setting the workspace to a number greater than 1.

**Expected behavior**
Should behave similar to before and open on the current workspace

**System information:**
 - Distro: `Linux nixos 6.6.31 #1-NixOS SMP PREEMPT_DYNAMIC Fri May 17 10:02:40 UTC 2024 x86_64 GNU/Linux`
- Compositor: Hyprland 0.40.0-unstable-2024-05-12
 - Ironbar version: Tried 0.15.1 and latest commit https://github.com/JakeStanger/ironbar/commit/4ad4b0e070cc4e271251763db7210e70857d68ca

**Configuration**
https://github.com/donovanglover/nix-config/blob/50d788ab4d79d5896c4a046c6242b49b5ea5db08/home/ironbar.nix

**Additional context**
Seems to also be an issue with eww so might be a Hyprland bug.

**Comment by donovanglover** [comment]
Probably fixed by https://github.com/hyprwm/Hyprland/pull/6089 and shouldn't be an ironbar issue. Haven't tested yet but feel free to close.

**Comment by JakeStanger** [comment]
Ironbar just calls `gtk-open`, so it's fully up to the compositor to decide what to do with the window. I'll close this one

**Comment by donovanglover** [comment]
For anyone else wondering, this is a known issue and expected behavior. The workaround is to change [`initial_workspace_tracking`](https://wiki.hyprland.org/Configuring/Variables/#misc) to 0.

Related:

- https://github.com/hyprwm/Hyprland/issues/6124
- https://github.com/hyprwm/Hyprland/issues/6128
- https://github.com/hyprwm/Hyprland/issues/5919
- https://github.com/hyprwm/Hyprland/issues/6102#issuecomment-2116333269
