### ISSUE TITLE
Dialog Menus show up in launcher

### ISSUE THREAD

**Issue by ClaireNeveu** [JakeStanger/ironbar#606]
**Describe the bug**
Sub-windows in an application (like dialog menus) appear in the launcher when open.

**To Reproduce**
1. Open VS Code
2. Right click in the file editor
3. Observe that a new item appears in the launcher

**Expected behavior**
The launcher should not display a new item.

**System information:**
 - Distro: Arch Linux
- Compositor: Hyprland 0.40.0
 - Ironbar version: 0.16.0-pre

**Configuration**
> Share your bar configuration and stylesheet as applicable:

<details><summary>Config</summary>

```

```
</details>

<details><summary>Styles</summary>

```css

```
</details>

**Additional context**
This might be related to Krita getting stuck in the launcher since it opens a lot of subwindows.

**Screenshots**
> If applicable, add screenshots to help explain your problem.

**Comment by ClaireNeveu** [comment]
Still working on getting a minimum repro on the Krita issue, it doesn't happen if you close Krita right away but consistently after I've been drawing for an hour or two and close it, ironbar thinks it's still running until I restart ironbar.

**Comment by JakeStanger** [comment]
I've got a feeling this is going to be an easy fix, or nigh impossible. Out of interest, do you know whether krita is native or xwayland?

**Comment by ClaireNeveu** [comment]
Krita is an xwayland app.

**Comment by JakeStanger** [comment]
In theory, I think it should be possible to detect if a window has a parent window using `wlr_foreign_toplevel_management`, which is already hooked up. This means it *should* be easy.

As far as I can see though, Hyprland never sends that info, so I need to dig a bit deeper and see if another compositor does and if it'll help.

As an aside, I had krita open to test and hit the same bug where it doesn't close properly. I did open a single dialog. It seems strange I've never seen this occur with anything else. My Jetbrains IDEs are all xwayland and spam child windows like nothing else so I don't think that's the culprit.

**Comment by ClaireNeveu** [comment]
Hmm, this might be a bug in Hyprland, they just did a big rewrite with 0.40.0.

**Comment by JakeStanger** [comment]
...and an even bigger one with 0.41.0. Hyprland isn't particularly stable right now as a result, but I'd be interested to know if you still have the issue after updating.

**Comment by ClaireNeveu** [comment]
This does still happen on 0.41.x

**Comment by ClaireNeveu** [comment]
0.41.x is even more broken than 0.40.x it seems so take that for what it is.

**Comment by donovanglover** [comment]
Also occurs with 0.41.2 and hovering over links that have titles in xwayland chromium

**Comment by JakeStanger** [comment]
Still occurs in v0.42.0

I've seen this quite a few times with different apps myself and every time it seems to be xwayland. A little bit of digging seems to show that these are created as xwayland windows with no title/class. 

I'm going to try filtering those out and we'll see if that sorts it. At the very least, it should help mitigate it.

**Comment by JakeStanger** [comment]
This seems to have caught all the examples I know of, at least. Any further issues let me know and I'll re-open.
