### ISSUE TITLE
[Example config]: k10temp_Tccd1 does not work for me

### ISSUE THREAD

**Issue by ToxicMushroom** [JakeStanger/ironbar#607]
**Describe the bug**
The example configs all contain k10temp_Tccd1 with an underscore.
Wiki mentions it should be a hyphen: k10temp-Tccd1.
After changing my sensor in my config to use the hyphen it works.

**To Reproduce**
1. Have amd cpu with Tccd1 sensor
2. Load default config
3. No temp readings
4. Change the underscore to a hyphen in the sensor id 
5. profit

**Expected behavior**
Either both should work or the default configs should be fixed

**System information:**
 - Distro: Arch linux
- Compositor: Hyprland
 - Ironbar version: 0.16.0-pre 

**Configuration**
https://github.com/JakeStanger/ironbar/blob/b0d3bfd6d9545f794e532d34f255823205ef6a40/examples/config.toml

**Screenshots**
![image](https://github.com/JakeStanger/ironbar/assets/32853531/d5126389-ef02-43f0-8601-115ea76fbdd9)

![image](https://github.com/JakeStanger/ironbar/assets/32853531/ded36d3d-dcc9-4c3f-be02-76a1acf4ac62)

**Comment by JakeStanger** [comment]
The wiki is correct, the examples need correcting.

I'm also looking at improving this as part of the next update in #142.
