### ISSUE TITLE
[Question] How to change the device-box-label color?

### ISSUE THREAD

**Issue by madfanat** [JakeStanger/ironbar#615]
**Question**
I just want to change the background color of the label in the device box to make it look unified. Seems to have tried every option available, but without success. Could you please tell me which selector and setting should be used?
P.S. now it has the same color as any background.
 
![screenshot](https://github.com/JakeStanger/ironbar/assets/168630462/7b54d0d6-8a22-4cfc-a2fc-c60b1537e376)

**Comment by JakeStanger** [comment]
You can use `cellview` to target the dropdown component (including options), and `arrow` for the arrow. Does that do what you want?

**Comment by madfanat** [comment]
Thanks, it does the trick.
