### ISSUE TITLE
[Launcher] Applications with multiple windows stay focused when window is closed

### ISSUE THREAD

**Issue by donovanglover** [JakeStanger/ironbar#618]
**Describe the bug**
When opening two windows of the same application, the application stays in a focused state when one of the windows is closed

**To Reproduce**
1. Open kitty/thunar/etc. on workspace 1
2. Open a new kitty/thunar/etc. window and put it on workspace 2
3. Close one of the two windows
4. Focused state persists when workspace is empty

**Expected behavior**
Should not show up as focused when window is closed

**System information:**
 - Distro: NixOS 24.05 at https://github.com/NixOS/nixpkgs/commit/805a384895c696f802a9bf5bf4720f37385df547
- Compositor: Hyprland v0.40.0
 - Ironbar version: Latest commit from yesterday at https://github.com/JakeStanger/ironbar/commit/6edfe940000d1a54a92fb71dd6254909724f9307
 
 **Additional context**
 Also possible to reproduce with a single workspace and 2 different applications open, which results in both of them having the focused state

**Comment by JakeStanger** [comment]
Should be resolved, cheers for reporting. I believe this came about because Hyprland 0.40 has altered how it sends events for closing windows and I was not correctly handling said events.

**Comment by donovanglover** [comment]
Thanks!
