### ISSUE TITLE
[Launcher] Focus action not working in Hyprland v0.40.0

### ISSUE THREAD

**Issue by donovanglover** [JakeStanger/ironbar#624]
**Describe the bug**
Not able to click on applications to focus them in Hyprland v0.40.0

**To Reproduce**
1. Open a few applications
2. Try to focus them by clicking on their icons
3. Nothing happens

**Expected behavior**
Should work like in Hyprland v0.39.1

**System information:**
 - Distro: NixOS 24.05 at https://github.com/NixOS/nixpkgs/commit/805a384895c696f802a9bf5bf4720f37385df547
- Compositor: Tried Hyprland v0.40.0 in 24.05 and https://github.com/hyprwm/Hyprland/commit/0ebb43c1a37e7321e5ed7223ea85ed555cc82735
 - Ironbar version: Tried 0.15.1 and https://github.com/JakeStanger/ironbar/commit/6edfe940000d1a54a92fb71dd6254909724f9307

**Configuration**

Possible to reproduce with [nix-config](https://github.com/donovanglover/nix-config/tree/ca4e454138be3fbdabfd1da787ce8c347231f2bd) by removing the hyprland overlay and rebuilding with nixpkgs changed to `nixos-24.05`

**Additional context**

- https://github.com/hyprwm/Hyprland/issues/6236

**Comment by JakeStanger** [comment]
This looks like a Hyprland bug to me:

- With vanilla Hyprland 0.40, the bug is present
- Using the [hy3](https://github.com/outfoxxed/hy3) plugin, it works fine

**Comment by donovanglover** [comment]
Fixed by changing `misc:focus_on_activate` to `true`. Seems like `wlr_foreign_toplevel_management` got changed a bit in 0.40.0.

See: https://github.com/hyprwm/Hyprland/issues/5939
