### ISSUE TITLE
Launcher icons dont focus on click

### ISSUE THREAD

**Issue by crimsonduelist** [JakeStanger/ironbar#635]
**Describe the bug**
> When I click on one of the icons on the launcher module it will not change focus.
If multiple of that app are open it does indeed pop up with multiple options but again clicking on one will not change focus.

**To Reproduce**
1. configure iron bar with launcher module and open ironbar 
2. Click on an icon from the launcher module on ironbar

**Expected behavior**
> Focus should change to that icon s corresponding app

**System information:**
 - Distro: Arch Linux
- Compositor: Hyprland
 - Ironbar version: ironbar 0.16.0-pre

**Configuration**
> Share your bar configuration and stylesheet as applicable:

<details><summary>Config</summary>

```
{
  "position": "top",
  "height": 30,
  "start": [
    {
      "type": "workspaces",
      "all_monitors": true,
      "icon_size":15
    },
    {
      "type": "launcher",
      "show_names": false,
      "show_icons": true,
      "icon_size":20

    }
  ],
  "center": [],
  "end": []
}

```
</details>

>I ve got no custom styles

<details><summary>Styles</summary>

```css

```
</details>

**Additional context**
> Add any other context about the problem here.

**Screenshots**
> If applicable, add screenshots to help explain your problem.

attaching the log cuz exceeding 65536 characters
[ironbar.2024-06-10.log](https://github.com/user-attachments/files/15768215/ironbar.2024-06-10.log)

**Comment by JakeStanger** [comment]
This sounds like a duplicate of https://github.com/JakeStanger/ironbar/issues/624, can you confirm pls?

**Comment by crimsonduelist** [comment]
indeed
