### ISSUE TITLE
[Launcher] Focused windows should minimize when ironbar launcher icon is clicked

### ISSUE THREAD

**Issue by winteriscariot** [JakeStanger/ironbar#658]
Maybe there's an option to make this function as I expect it to. Most docks seem to operate this way:

* Click application icon to focus window
* Click same icon again to minimize window

Is it possible to do this currently?

**Comment by JakeStanger** [comment]
What compositor are you using>

**Comment by winteriscariot** [comment]
[labwc ](https://github.com/labwc/labwc)

**Comment by JakeStanger** [comment]
Ah okay then yes would make sense to add
