### ISSUE TITLE
[Notifications] Module state not updating

### ISSUE THREAD

**Issue by donovanglover** [JakeStanger/ironbar#674]
**Describe the bug**
Notifications module doesn't update when swaync status changes

**To Reproduce**
1. Use swaync with ironbar's notifications module
2. Observe how the numbers don't update until restarting ironbar

**Expected behavior**
Should update without having to restart ironbar

**System information:**
 - Distro: NixOS unstable
- Compositor: Hyprland
 - Ironbar version: https://github.com/JakeStanger/ironbar/commit/58190ab079d00dd53babb72346f1da6e1cc9ac72

**Comment by JakeStanger** [comment]
Looks like I broke it fixing a compiler warning. Fix incoming
