### ISSUE TITLE
More types of widgets for the custom module

### ISSUE THREAD

**Issue by ttoino** [JakeStanger/ironbar#68]
When configuring custom modules for stuff like volume/brightness/battery/etc. the current selection of widgets is really limiting, I would especially like a slider/progress bar for these situations.

**Comment by JakeStanger** [comment]
Agreed, more options is definitely something on the table.

What widgets other than sliders and progress bars do you think would be good to add in?

**Comment by ttoino** [comment]
I haven't really found a use for other widgets, but maybe other form elements like textfields and comboboxes, but I don't know how useful these would actually be in the context of a bar. Maybe to implement a command launcher?

**Comment by yavko** [comment]
Also, circular progress like in [eww](https://github.com/elkowar/eww/pull/328) would be cool

**Comment by JakeStanger** [comment]
Force pushing really messed up the references huh. 

Okay here's where I'm at with this: PR #104 adds the initially requested slider and progress bar widgets. 

I have held off the other form elements for two reasons:

- They're complex and would be tricky to get right. For example, when/how should the text box value be sent to a script? If it was every keystroke that could make the script logic more complex. If it was on a button click/unfocus that may not be intuitive and would require a lot of logic for a niche feature.
- Based on the above, I'd consider these to be out of scope of the bar. A command launcher for example should be its own separate program.

The circular progress in eww (thanks for the link) uses Cairo under the hood. I reckon there's opportunity to do some really cool things with that, so I'll hold off for now and do some planning. I'm considering that out of scope for this issue though.

**Comment by yavko** [comment]
> The circular progress in eww (thanks for the link) uses Cairo under the hood. I reckon there's opportunity to do some really cool things with that, so I'll hold off for now and do some planning. I'm considering that out of scope for this issue though, so feel free to open a new dedicated one.

Ah, can't wait!
