### ISSUE TITLE
Tooltip script embedding doesn't respect ordering

### ISSUE THREAD

**Issue by JustSimplyKyle** [JakeStanger/ironbar#69]
**Describe the bug**
> title
![image](https://user-images.githubusercontent.com/68589851/217828610-57c0d5eb-1688-49dc-940e-f70402574950.png)

**To Reproduce**
set this somewhere in config ` tooltip = "{{~/.config/ironbar/scripts/ram_info}} GiB"`
the bug happened

**Expected behavior**
I would like it to be 14.475 GiB

**System information:**
 - Arch Linux
- Hyprland
 - Ironbar version: 0.1.0

**Configuration**
> Share your bar configuration and stylesheet as applicable:

https://gitea.com/SimplyKyle/dotfiles/src/branch/main/home/.config/ironbar

**Additional context**
Haven't used ironbar in a while, might be a configuration error

**Comment by JakeStanger** [comment]
Weird, I'll have a look into that. Thanks for reporting
