### ISSUE TITLE
Notification tray module

### ISSUE THREAD

**Issue by JakeStanger** [JakeStanger/ironbar#7]
Would be cool to be able to connect to notification daemons and keep track of past notifications, displaying them in a popout panel/tray of sorts.

**Comment by yffengdong** [comment]
related issues: support SwayNotificationCenter
https://github.com/ErikReider/SwayNotificationCenter

**Comment by JakeStanger** [comment]
This is probably the easiest way to go about it and something I've been considering for a while. I don't know if it's possible to hook into its daemon, but at the very least I can provide a (custom) module which opens it up.

**Comment by yavko** [comment]
> This is probably the easiest way to go about it and something I've been considering for a while. I don't know if it's possible to hook into its daemon, but at the very least I can provide a (custom) module which opens it up.

From taking a 15.73 second peak at the codebase I can confirm it is possible, and it's done through dbus.

**Comment by ErikReider** [comment]
> related issues: support SwayNotificationCenter [ErikReider/SwayNotificationCenter](https://github.com/ErikReider/SwayNotificationCenter)

I'd be down to work with you on this for swaync! :)

**Comment by JakeStanger** [comment]
Oh damn, the legend himself! That'd be really appreciated, thanks. I'll be coming to this issue soon-ish (read: within a few months) so now's actually a good time to really start planning the details on it.

My thoughts on this currently are that Ironbar shouldn't be treading on SwayNC's toes too much, and should only really be supplementing it with the bar integration. In real terms that means I see Ironbar being able to respond to new notifications and show info on the bar such as the latest notification or a total count, and provide a button which opens the notification panel. Communicating via dbus will work nicely.

I'm not sure if there's any other functionality I'm missing that people could see as useful?

**Comment by ErikReider** [comment]
> In real terms that means I see Ironbar being able to respond to new notifications and show info on the bar such as the latest notification or a total count, and provide a button which opens the notification panel. Communicating via dbus will work nicely.

Swaync provides stable dbus methods that can easily be used by ironbar :)
![image](https://github.com/JakeStanger/ironbar/assets/35975961/b3c6db4e-5065-4926-93ae-916c9c0c351f)

Another thing would be to maybe export some GTK widgets as a library or something that others can use? So just attaching the "control center widget" to a popup on click? Not really sure about this though...

**Comment by JakeStanger** [comment]
Good news about the dbus methods, looks like we're covered. I did have a good look at those before (as did Yakvo I assume) so good to have that reinforced.

> Another thing would be to maybe export some GTK widgets as a library or something that others can use? So just attaching the "control center widget" to a popup on click? Not really sure about this though...

There could be an interesting approach to this, which would be to decouple the UI and daemon, perhaps allowing 3rd party UIs to more easily hook in. I'm not sure how feasible or beneficial or sensible that'd be though, especially given D-Bus is already an option. This could risk a crossing of the responsibilities of each program, unless I'm misunderstanding. My belief here is that `swaync` should be responsible for notifications, `ironbar` (or other) should be responsible for talking to it, and it should be kept to that strict server/client model.

If I've not quite grasped what you're suggesting or you've other ideas though I'm open to anything!

**Comment by JakeStanger** [comment]
@ErikReider I've succesfully managed to talk to SwayNC and can do the basics already :tada: but the subscribe method seems fairly limited at the moment. It looks like it just comes back with the following bits:

```xml
<signal name="SubscribeV2">
  <arg type="u" name="count"/>
  <arg type="b" name="dnd"/>
  <arg type="b" name="cc_open"/>
  <arg type="b" name="inhibited"/>
</signal>
```

but as far as I can see there's no way to get the notification body itself. Is there a way I'm missing, or is this something you think could be added (lmk and I can open an issue your end to track)?

**Comment by JakeStanger** [comment]
In the meantime, an initial implementation of the widget is pretty much ready to be shipped in the above PR.

**Comment by ErikReider** [comment]
> but as far as I can see there's no way to get the notification itself. Is there a way I'm missing, or is this something you think could be added (lmk and I can open an issue your end to track)?

Yeah, that's on purpose so that other applications can't snoop on the users notifications. Are there any other properties that you would like to be returned?

**Comment by JakeStanger** [comment]
Oh that makes a lot of sense. Everything else I have covered, and to be honest the would-be-nice of the title makes less sense the more I think aobut it - notifications are obviously on screen, so why duplicate that on the bar?
