### ISSUE TITLE
Support for onhover Module-level options

### ISSUE THREAD

**Issue by JustSimplyKyle** [JakeStanger/ironbar#70]
**Is your feature request related to a problem? Please describe.**
I could *barely* script this using `hyprctl cursorpos` but it's just too ugly and spamming sockets generally isn't a good idea.

**Describe the solution you'd like**
More specifically, `onhover` and `onhoverlost`. Using `script [oneshot]` is fine, but I would like to propose an alternate solution.
Add support for variables, like eww's defvar
![image](https://user-images.githubusercontent.com/68589851/217831302-977fe422-3107-49f7-9a5f-9edfdcdc310e.png)
this would reduce the required scripting to make it work. Without this, I would have to use external scripts to save the state into a lock, which works, but get tedious real quickly.
Although this feature is probably out of scope to this issue anyway

**Comment by JakeStanger** [comment]
Adding mouse enter/exit events should be very straightforward, so happy to do that.

Eww style variables is something that could be considered further down the line, but they'd need to be discussed and scoped out in more detail (including how they'd integrate with the existing systems). Feel free to open a dedicated issue/discussion for those.
