### ISSUE TITLE
Support for revealer

### ISSUE THREAD

**Issue by JustSimplyKyle** [JakeStanger/ironbar#72]
**Is your feature request related to a problem? Please describe.**
I want animations!(top is eww, bottom is ironbar)
[Kooha-2023-02-10-12-48-53.webm](https://user-images.githubusercontent.com/68589851/218003441-8244e8a8-18c0-4469-b8bf-ae1f405a3de0.webm)

**Describe the solution you'd like**
I'm actually not sure how would this be implemented
it could be added to widget_type in https://github.com/JakeStanger/ironbar/wiki/custom 

**Additional context**
There is issue https://github.com/JakeStanger/ironbar/issues/68, but I feel like given the aspect of this respect that this should be in a separate issue

**Comment by JakeStanger** [comment]
There might be an easy solution here to wrap every module inside a `Revealer` that hooks into `show_if`. You'd then be able to target that with CSS. 

I could also probably do the same with the box widget in the custom module. I'm not sure if there's any explicit need for it to be its own widget type?

**Comment by JustSimplyKyle** [comment]
> target that with CSS

If I just slap a transition css on it and would it work?

And yeah, probably not worth being its own widget type

**Comment by JakeStanger** [comment]
> If I just slap a transition css on it and would it work?

I've never played with the GTK revealer before, and Google isn't being super helpful on this one. It definitely has [a few built-in options](https://docs.gtk.org/gtk3/enum.RevealerTransitionType.html) you can choose from at least.

I will have a look and see what can be done with it and how Eww does it.
