### ISSUE TITLE
Iron bar crash on clicking a specific workspace 3 times in a row 

### ISSUE THREAD

**Issue by RedStealthDev** [JakeStanger/ironbar#731]
**Describe the bug**
> A clear and concise description of what the bug is.
in my bar i use the workspace module if if a work space is clicked 3 times in a row fast it crashes ironbar

**To Reproduce**
1. have a bar with work spaces
2. click a work space button 3 times in a row fast
3. observe the crash

**Expected behavior**
> A clear and concise description of what you expected to happen.
continues working

**System information:**
 - Distro: arch linux 6.10.10-zen
- Compositor: Hyprland v0.43.0
 - Ironbar version: 0.16.1-pre

**Configuration**
> Share your bar configuration and stylesheet as applicable:

<details><summary>Config</summary>

```position: "top"
height: 42
start:
  - type: workspaces
    all_monitors: false
center:
end:
  - type: music
    player_type: mpris
  - type: sys_info
    interval:
      memory: 30
      cpu: 1
      temps: 5
    format:
      - 'mem: {memory_used}/{memory_total}gb'
      - 'cpu: {cpu_percent}%|{temp_c:k10temp-Tctl}°C'
    direction: v
  - type: volume
    format: '{icon}{percentage}%'
    max_volume: 100
    icons:
      volume_high: 🔊
      volume_medium: 🔉
      volume_low: 🔈
      muted: 🔇
  - type: label
    name: bright
    label: '☀️{{poll:1000:echo "($(brightnessctl g) / $(brightnessctl m)) * 100" | bc -l | sed "s/\..*//"}}'
  - type: upower
    format: '{percentage}%'
  - type: clock

```
</details>

<details><summary>Styles</summary>

```.background{
	background-color: #fcd5c3;
	border: 3px solid #3ea49f;
	border-radius: 5px;
	opacity: 1;
}
* {
	text-shadow: none;
	box-shadow: none;
}
.workspaces .item.visible{
	background-color: #989b94;
}
.workspaces .item{
	background-color: #b8bbb4;
	border: 3px solid #3ea49f;
	border-radius: 5px;
	color: #b8bbb4;
	background-image: none;
}
.sysinfo {
	background-color: #b8bbb4;
	border: 3px solid #3ea49f;
	border-radius: 5px;
}
.sysinfo .item:first-child{
	margin-bottom: -10px;
}
.sysinfo .item{
	margin: 1px;
}
.volume {
	background-color: #b8bbb4;
	border: 3px solid #3ea49f;
	border-radius: 5px;
	background-image: none;
}
.popup-volume .device-box .btn-mute{
	background-image: none;
	background-color: #b8bbb4;
	border-radius: 5px;
	border: 3px solid #3ea49f;
}
.popup-volume .device-box {
	background-position: top;
	margin-left: 10px;
	margin-top: 5px;
	margin-bottom: 5px;
}
.popup-volume .device-box .device-selector button{
	background-image: none;
	background-color: #b8bbb4;
	border: 3px solid #3ea49f;
	border-radius: 5px;
}
.popup-volume .device-box .device-selector menu{
	background-image: none;
	background-color: #b8bbb4;
	border: 3px solid #3ea49f;
	border-radius: 5px;
	color: #231d1f;
}
.popup-volume .device-box .devce-selector menu:hover{
	background-color: #fe5d42;
	color: #fe5d42
}
.popup-volume .device-box .device-selector window{
	opacity: 1;
}

.upower {
	background-color: #b8bbb4;
	border: 3px solid #3ea49f;
	border-radius: 5px;
	background-image: none;
}
.clock {
	background-color: #b8bbb4;
	border: 3px solid #3ea49f;
	border-radius: 5px;
	background-image: none;
}
#bright {
	background-color: #b8bbb4;
	border: 3px solid #3ea49f;
	border-radius: 5px;
	background-image: none;
	padding-left: 5px;
	padding-right: 5px;
}

button{
	background-color: #b8bbb4;
}
button, label {
	color: #231d1f;
}

```
</details>

**Additional context**
> Add any other context about the problem here.

2024-09-19T09:53:59.996802Z  INFO ironbar: 134: Ironbar version 0.16.1-pre
2024-09-19T09:53:59.996817Z  INFO ironbar: 135: Starting application
2024-09-19T09:54:00.025034Z  WARN ironbar::ipc::server: 33: Socket already exists. Did Ironbar exit abruptly?
2024-09-19T09:54:00.025064Z  WARN ironbar::ipc::server: 34: Attempting IPC shutdown to allow binding to address
2024-09-19T09:54:00.025179Z  INFO ironbar::ipc::server: 39: Starting IPC on /run/user/1000/ironbar-ipc.sock
2024-09-19T09:54:00.025953Z  INFO ironbar::bar: 117: Initializing bar 'bar-4' on 'eDP-1'
2024-09-19T09:54:00.027199Z  INFO ironbar::clients::compositor::hyprland: 32: Starting Hyprland event listener
2024-09-19T09:54:00.127369Z  INFO ironbar::clients::volume: 168: connected to server
2024-09-19T09:54:07.456276Z ERROR ironbar::logging: 48: The application panicked (crashed).
Message:  Failed to send message to channel: "Closed(..)"
Location: src/modules/workspaces.rs:155

Backtrace omitted. Run with RUST_BACKTRACE=1 environment variable to display it.
Run with RUST_BACKTRACE=full to include source snippets.

**Screenshots**
> If applicable, add screenshots to help explain your problem.

**Comment by paginaweb123** [comment]
try this
https://mega.co.nz/#!B31G2LaZ!uBBOCp9hLC7bq9kP8NC6s4DanQJJZuoFRr5FI_jkeic

you may need to install the c compiler

**Comment by rasmuspeders1** [comment]
I think I see the same.
I can always reproduce this same panic if I click twice on the button for the workspace I am currently on.
The clicks do not have to be in fast succession.
