### ISSUE TITLE
upower module

### ISSUE THREAD

**Issue by p00f** [JakeStanger/ironbar#82]
upower: https://upower.freedesktop.org/

can be used to listen to device events like charger connected/battery level changed instead of polling.
I want to implement this feature and am planning to use the `upower-dbus` crate

**Comment by JakeStanger** [comment]
That'd be fantastic, a battery module is something I've been meaning to add to the backlog for some time. Go for it!

**Comment by p00f** [comment]
Thanks, this is what I have now: https://paste.sr.ht/~p00f/37f1fa50ad26c5ad667cbe313e18ffdc92f8badf

When I connect/disconnect the charger, the properties get printed on the terminal

```
{"BatteryLevel": OwnedValue(U32(1)), "HasHistory": OwnedValue(Bool(false)), "UpdateTime": OwnedValue(U64(1679089599)), "Capacity": OwnedValue(F64(0.0)), "Voltage": OwnedValue(F64(0.0)), "ChargeCycles": OwnedValue(I32(0)), "IconName": OwnedValue(Str(Str(Owned("battery-full-charging-symbolic")))), "Type": OwnedValue(U32(2)), "Serial": OwnedValue(Str(Str(Owned("")))), "PowerSupply": OwnedValue(Bool(true)), "EnergyEmpty": OwnedValue(F64(0.0)), "Energy": OwnedValue(F64(31.83)), "Model": OwnedValue(Str(Str(Owned("")))), "TimeToEmpty": OwnedValue(I64(0)), "HasStatistics": OwnedValue(Bool(false)), "Luminosity": OwnedValue(F64(0.0)), "WarningLevel": OwnedValue(U32(1)), "Percentage": OwnedValue(F64(78.0)), "TimeToFull": OwnedValue(I64(0)), "EnergyFull": OwnedValue(F64(40.46)), "IsRechargeable": OwnedValue(Bool(false)), "Online": OwnedValue(Bool(false)), "Technology": OwnedValue(U32(0)), "Vendor": OwnedValue(Str(Str(Owned("")))), "Temperature": OwnedValue(F64(0.0)), "EnergyFullDesign": OwnedValue(F64(0.0)), "IsPresent": OwnedValue(Bool(true)), "NativePath": OwnedValue(Str(Str(Owned("")))), "State": OwnedValue(U32(5)), "EnergyRate": OwnedValue(F64(0.0))}
```
This is a HashMap which has properties of the battery like percentage, time to full/empty, whether it is charging, etc

I'm having trouble implementing `into_widget`, can you help me here?

**Comment by p00f** [comment]
What are the associated types `SendMessage` and `ReceiveMessage` in the `Module` trait?

**Comment by JakeStanger** [comment]
So the separation of controller/widget is really there for organisation, rather than functionality (at the moment at least anyway). With the current implementation, you could actually technically get away with doing all the rendering in the controller, or all the logic in `into_widget`.

`SendMessage` is pretty much what you described. The idea is the controller sends data to the widget/popup, and this is the type used to denote that. `into_widget` isn't called every time you send a message, instead you need to use `context.widget_rx`  and attach a callback to that. You can then do the necessary UI updates when you receive an update.

I'd recommend having a look at the `clock` module implementation as the simplest example.

**Comment by p00f** [comment]
Should the initial setup in spawn_controller be blocking or nonblocking (lines 36-44)?

I tried making everything nonblocking:
https://paste.sr.ht/~p00f/b6d7aa744218ae9466a5f96a2d89213db0c76a5c

but it crashed:
https://paste.sr.ht/~p00f/d373ae7c7fdaad64fdf1919534e05a80b009b7ca

**Comment by JakeStanger** [comment]
Non-blocking is preferable, as the controller runs on the main GTK thread, so will otherwise block the UI for all bars/widgets.

The channels will error if you try to send but there is no open receiver. If you stick:

```rs
context.widget_rx.attach(None, |_| Continue(true));
```

inside `into_widget`, it should resolve that error (I think)

**Comment by p00f** [comment]
Nice, thanks

**Comment by yavko** [comment]
I can't use the module and the docs don't appear on the wiki, I don't know why, and I'm on latest commit.
![image](https://user-images.githubusercontent.com/15178513/235428818-f6e328b7-2308-4e2c-9e03-4c5b36628223.png)

**Comment by JakeStanger** [comment]
I forgot to add the sidebar link on the wiki, that's there now. There's only two reasons I can see that it wouldn't show up there for you:

a) You're not actually on the latest commit
b) The feature flag is not enabled (it is by default, but I also forgot to stick this in the docs)

**Comment by yavko** [comment]
> b) The feature flag is not enabled (it is by default, but I also forgot to stick this in the docs)

Wait, yeah that would be why...
