### ISSUE TITLE
Always visible workspaces

### ISSUE THREAD

**Issue by yavko** [JakeStanger/ironbar#90]
**Is your feature request related to a problem? Please describe.**

I kinda just want 10 workspaces always showing

**Describe the solution you'd like**

An option that allows setting a range of workspaces, that are always shown

**Describe alternatives you've considered**

Maybe a list of workspaces instead?

**Comment by JakeStanger** [comment]
Hm, this will be a bit fiddly but I can see the value. 

I reckon the best way would probably be to use the existing `name_map` option, and add some flag along-side that to toggle filtering the entries based on open workspaces. 

I think that way it should play nicely with `all_monitors` too.

**Comment by yavko** [comment]
> Hm, this will be a bit fiddly but I can see the value.
> 
> I reckon the best way would probably be to use the existing `name_map` option, and add some flag along-side that to toggle filtering the entries based on open workspaces.
> 
> I think that way it should play nicely with `all_monitors` too.

Yeah, actually that would be better, maybe making `name_map` check if the value is either a string or object, then a prop like `always_shown`, and `text` for what it should appear as

**Comment by yavko** [comment]
Oh, yeah, this should also add a new CSS class for inactive ones.

**Comment by Gajus84** [comment]
And maybe also the possibility to do the opposite too. Workspaces that are always hidden. Hyprlands Special Workspaces for example.

**Comment by Gajus84** [comment]
> Assuming the Hyprland IPC exposes whether a workspace is special, filtering those should be trivial.

It does via `createworkspace>>special:"name"`.

**Comment by yavko** [comment]
Ironbar uses Hyprland-rs which uses a ADT for workspace creation events, should be even easier

**Comment by yavko** [comment]
I'm going to try implementing this, if thats okay

**Comment by JakeStanger** [comment]
Absolutely, go for it!

My currently thoughts on this are that the best way to tackle it would be to add a new option, similar to the `favourites` launcher widget option. That can just take an array of workspace names and pre-populate the workspaces with those. 

I think I prefer that to having `name_map` have two separate formats, and two separate responsibilities. My fear is otherwise the logic becomes more complex than it needs to be, and it becomes more complicated to configure.

For special workspaces, it might make sense to either just add in logic to always ignore it, or add a new `ignore_special` option.

**Comment by yavko** [comment]
> My currently thoughts on this are that the best way to tackle it would be to add a new option, similar to the `favourites` launcher widget option. That can just take an array of workspace names and pre-populate the workspaces with those.

On it

> I think I prefer that to having `name_map` have two separate formats, and two separate responsibilities. My fear is otherwise the logic becomes more complex than it needs to be, and it becomes more complicated to configure.

Oh, time to scrap that then

> For special workspaces, it might make sense to either just add in logic to always ignore it, or add a new ignore_special option.

I forgot, time to add that too

**Comment by yavko** [comment]
I've encountered an issue, since by design these workspaces don't exist in the compositor, there is no way to know their `monitor` or their `id`, so how do I decide where to show them? Should it instead be an array of maps?

**Comment by JakeStanger** [comment]
I'd say a map of monitor names to workspaces to include would be clearest:

So to always show workspaces 1 and 2 on DP-1, and always show 3 and 4 on DP-2:
```json
{
"favorites": {
    "DP-1": [ "1", "2" ],
    "DP-2": [ "3", "4" ]
  }
}
```

The only problem with that is that if you have separate configs per monitor, or if you have `all_monitors` enabled, you're going to end up duplicating that. So I'd say this is a case where accepting two formats would make sense? So `favorites` can also take just an array of names, in which case it would apply it to all monitors:

To always show 1, 2, 3 and 4 regardless of monitor:
```json
{
"favorites": ["1", "2", "3", "4"]
}
```

Again, I'm open to ideas here - if you have other thoughts do let me know (or just run with them and I'll pick them up in the morning).

**Comment by yavko** [comment]
> The only problem with that is that if you have separate configs per monitor, or if you have `all_monitors` enabled, you're going to end up duplicating that. So I'd say this is a case where accepting two formats would make sense? So `favorites` can also take just an array of names, in which case it would apply it to all monitors:

Yeah that's probably the best way
