### ISSUE TITLE
Control ironbar at runtime

### ISSUE THREAD

**Issue by yavko** [JakeStanger/ironbar#91]
**Is your feature request related to a problem? Please describe.**

I would like to reload my ironbar config, would also be cool to change config settings at runtime

**Describe the solution you'd like**

A IPC socket for ironbar that listens on a socket, and a basic cli tool for communicating with it

**Describe alternatives you've considered**

Maybe TCP? But TCP is slower and is harder to locate, since you have to use ports.

**Additional context**

I think Hyprland does it well, so maybe that could lead to inspiration

**Comment by yavko** [comment]
> I'm not sure about changing config settings at runtime. I don't think it would be hugely complex to implement on top of hot-reloading, but I am not sure how much benefit it would have vs the complexity. What would you like to achieve with it, in case there's a different way we could go about it?

Honestly, I'ts just something I came up, I don't know how I would use it lol.

**Comment by yavko** [comment]
I came up with another must feature, support to open the gtk inspector

**Comment by JakeStanger** [comment]
I don't think you can do that programatically, or at least I cannot find anything on it. You can launch ironbar with the inspector with `GTK_DEBUG=interactive`.

**Comment by yavko** [comment]
> I don't think you can do that programatically, or at least I cannot find anything on it. You can launch ironbar with the inspector with `GTK_DEBUG=interactive`.

Well, eww can do it, though I have no clue how tho

**Comment by JakeStanger** [comment]
> Well, eww can do it, though I have no clue how tho

Turns out it's literally just:

```rs
gtk::Window::set_interactive_debugging(true)
```

:eyes:

**Comment by yavko** [comment]
I know this might seem useless, but actually it has a lot of use, but I think being able to load CSS at runtime shouldn't be too hard. I personally would use this to change the background of the music widget to a blurred background of the cover. Also, I saw the work done on the branch so far https://github.com/JakeStanger/ironbar/compare/master...feat/cli-ipc, seems great!

**Comment by JakeStanger** [comment]
> Also, I saw the work done on the branch so far https://github.com/JakeStanger/ironbar/compare/master...feat/cli-ipc, seems great!

Watch this space, some very interesting stuff coming in the next few days (assuming I have time...)

> I think being able to load CSS at runtime shouldn't be too hard

I can see the use for that, and yeah I think that's fairly trivial with CSS - it's already hot-loading anyway, so should just be a matter of adding more files to the mix.

**Comment by JakeStanger** [comment]
Tracking the branch in the draft PR https://github.com/JakeStanger/ironbar/pull/199 as we go to make it easier to follow along - suggestions and feedback as I go is very welcome, as I want to get this right before we merge it in.

Currently this includes a ping command, and a command to open the GTK inspector. I'm also tracking the dynamic variables from #71 but will keep discussion on those in that thread.

**Comment by yavko** [comment]
Another command idea: popup
Example: `ironbar popup open <name>`
I think being able to open popups from other places could be useful, I also think this can be supplemented with `popup:open:name` inside of buttons actually in ironbar

**Comment by JakeStanger** [comment]
Way ahead of you there ;) https://github.com/JakeStanger/ironbar/issues/71#issuecomment-1426882879

The implementation for this is a bit tricky, since modules and their popup control is fully self-contained, and relies on the module's location on the bar, so I'll probably get the main CLI/vars into master then work on that one separately.

**Comment by yavko** [comment]
Ah lol

**Comment by JakeStanger** [comment]
The base CLI and IPC are merged :tada: I will leave this open to track the couple of additional commands listed above, but for new ones pls stick those in their own issue.
