### ISSUE TITLE
Ability to hide music status icon in bar

### ISSUE THREAD

**Issue by yavko** [JakeStanger/ironbar#97]
**Is your feature request related to a problem? Please describe.**

I find it confusing that pause icon shows then playing (in bar), but in popup it shows the play icon, its super confusing

**Describe the solution you'd like**

just make a config option like `dont_invert_bar_icon` idk

**Describe alternatives you've considered**

no alternative

**Additional context**

screenshot in wiki shows them being opposite
https://github.com/JakeStanger/ironbar/wiki/music

**Comment by JakeStanger** [comment]
I don't think inverting it makes sense. 

The icon on the bar shows the current status (ie playing, paused), whereas in the popup it's a button that sends a command (ie play, pause). They're going to be opposites because if you're playing the command will be pause, and vice versa.

**Comment by yavko** [comment]
> The icon on the bar shows the current status (ie playing, paused), whereas in the popup it's a button that sends a command (ie play, pause). They're going to be opposites because if you're playing the command will be pause, and vice versa.

Well yeah, but I think it should be an option anyway, and maybe even disabling it on the bar would also be useful, so that when #72 is added, people can create their own that appears on hover as an example.

**Comment by JakeStanger** [comment]
I can see the use for an option to disable the icon on bar, and I'm happy to add that. 

I'm not particularly convinced adding the logic & complexity to invert it is worth it though, so unless future work surrounding icons makes that easier, I don't think I'm going to add that.
