### ISSUE TITLE
Set max bar size

### ISSUE THREAD

**Issue by yavko** [JakeStanger/ironbar#98]
**Is your feature request related to a problem? Please describe.**

I don't want my bar exceeding 32 pixels

**Describe the solution you'd like**

maybe a setting like `max-size: u16`

**Describe alternatives you've considered**

no alternatives

**Additional context**

![image](https://user-images.githubusercontent.com/15178513/229422151-8713ce3b-c5c2-48a5-a8a0-98fce711da48.png)
Ironbar is 10px taller, and I don't want that, I know I could probably fix by making sure nothing should be too big in CSS, but you know, sometimes we just want to be lazy? And plus waybar, and eww both have this.

**Comment by JakeStanger** [comment]
I think the top-level `height` option does what you want here.

https://github.com/JakeStanger/ironbar/wiki/configuration-guide#31-top-level-options

**Comment by yavko** [comment]
> I think the top-level `height` option does what you want here.
> 
> [JakeStanger/ironbar/wiki/configuration-guide#31-top-level-options](https://github.com/JakeStanger/ironbar/wiki/configuration-guide#31-top-level-options)

Oh sorry, I swear I couldn't find this lol
